package io.terminus.doctor.basic.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.common.enums.WareHouseType;
import io.terminus.doctor.basic.model.DoctorMaterialPriceInWareHouse;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 仓库中各物料每次入库的剩余量读服务
 * Date: 2016-08-15
 */

public interface DoctorMaterialPriceInWareHouseReadService {

    /**
     * 根据id查询仓库中各物料每次入库的剩余量
     * @param id 主键id
     * @return 仓库中各物料每次入库的剩余量
     */
    Response<DoctorMaterialPriceInWareHouse> findById(Long id);

    /**
     * 根据仓库id查询仓库中各物料每次入库的剩余量
     * @param wareHouseId 仓库id
     * @return 仓库中各物料每次入库的剩余量
     */
    Response<List<DoctorMaterialPriceInWareHouse>> findByWareHouseAndMaterialId(Long wareHouseId, Long materialId);

     /**
     * 查询各仓库当前库存的价值, 单位是“分”
     * 所有参数都可为空
     * @param farmId
     * @param warehouseId
     * @return key = warehouseId, value = 价值(分)
     */
     Response<Map<Long, Double>> stockAmount(Long farmId, Long warehouseId, WareHouseType type);

}
