package io.terminus.doctor.basic.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.basic.model.MaterialFactory;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 物资入库时可选择的厂家读服务
 * Date: 2016-09-29
 */

public interface MaterialFactoryReadService {

    /**
     * 根据id查询物资入库时可选择的厂家
     * @param materialFactoryId 主键id
     * @return 物资入库时可选择的厂家
     */
    Response<MaterialFactory> findMaterialFactoryById(Long materialFactoryId);

    /**
     * 查询唯一供货厂家
     * @param farmId
     * @param factoryName
     * @return
     */
    Response<MaterialFactory> findByFarmAndName(Long farmId, String factoryName);

    /**
     * 查询猪场所有的供货厂家
     * @param farmId
     * @return
     */
    Response<List<MaterialFactory>> findByFarmId(Long farmId);
}
