package io.terminus.doctor.warehouse.service;

import com.google.common.base.Throwables;
import io.terminus.common.model.Response;
import io.terminus.doctor.warehouse.dao.FeedFormulaDao;
import io.terminus.doctor.warehouse.model.FeedFormula;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 饲料配方表写服务实现类
 * Date: 2016-09-26
 */
@Slf4j
@Service
public class FeedFormulaWriteServiceImpl implements FeedFormulaWriteService {

    private final FeedFormulaDao feedFormulaDao;

    @Autowired
    public FeedFormulaWriteServiceImpl(FeedFormulaDao feedFormulaDao) {
        this.feedFormulaDao = feedFormulaDao;
    }

    @Override
    public Response<Long> createFeedFormula(FeedFormula feedFormula) {
        try {
            feedFormulaDao.create(feedFormula);
            return Response.ok(feedFormula.getId());
        } catch (Exception e) {
            log.error("create feedFormula failed, feedFormula:{}, cause:{}", feedFormula, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.create.fail");
        }
    }

    @Override
    public Response<Boolean> updateFeedFormula(FeedFormula feedFormula) {
        try {
            return Response.ok(feedFormulaDao.update(feedFormula));
        } catch (Exception e) {
            log.error("update feedFormula failed, feedFormula:{}, cause:{}", feedFormula, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.update.fail");
        }
    }

    @Override
    public Response<Boolean> deleteFeedFormulaById(Long feedFormulaId) {
        try {
            return Response.ok(feedFormulaDao.delete(feedFormulaId));
        } catch (Exception e) {
            log.error("delete feedFormula failed, feedFormulaId:{}, cause:{}", feedFormulaId, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.delete.fail");
        }
    }
}
