package io.terminus.doctor.warehouse.service;

import com.google.common.base.Throwables;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import io.terminus.doctor.warehouse.dao.MaterialFactoryDao;
import io.terminus.doctor.warehouse.model.MaterialFactory;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 物资入库时可选择的厂家读服务实现类
 * Date: 2016-09-29
 */
@Slf4j
@Service
@RpcProvider
public class MaterialFactoryReadServiceImpl implements MaterialFactoryReadService {

    private final MaterialFactoryDao materialFactoryDao;

    @Autowired
    public MaterialFactoryReadServiceImpl(MaterialFactoryDao materialFactoryDao) {
        this.materialFactoryDao = materialFactoryDao;
    }

    @Override
    public Response<MaterialFactory> findMaterialFactoryById(Long materialFactoryId) {
        try {
            return Response.ok(materialFactoryDao.findById(materialFactoryId));
        } catch (Exception e) {
            log.error("find materialFactory by id failed, materialFactoryId:{}, cause:{}", materialFactoryId, Throwables.getStackTraceAsString(e));
            return Response.fail("materialFactory.find.fail");
        }
    }

    @Override
    public Response<MaterialFactory> findByFarmAndName(Long farmId, String factoryName) {
        try {
            return Response.ok(materialFactoryDao.findByFarmAndName(farmId, factoryName));
        } catch (Exception e) {
            log.error("find materialFactory failed, cause:{}", Throwables.getStackTraceAsString(e));
            return Response.fail("materialFactory.find.fail");
        }
    }
}
