package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorDailyPig;
import org.springframework.stereotype.Repository;

import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪数量每天记录表Dao类
 * Date: 2017-04-17
 */
@Repository
public class DoctorDailyPigDao extends MyBatisDao<DoctorDailyPig> {

    public Boolean deleteBySumAt(Date date){
        return getSqlSession().delete(sqlId("deleteBySumAt"), ImmutableMap.of("sumAt", date)) == 1;
    }

}
