package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.common.utils.Dates;
import io.terminus.doctor.common.utils.DateUtil;
import io.terminus.doctor.event.model.DoctorBaseReport;
import io.terminus.doctor.event.model.DoctorDailyReport;
import io.terminus.doctor.event.model.DoctorDailyReportSum;
import org.springframework.stereotype.Repository;

import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 日报Dao类
 * Date: 2017-04-19
 */
@Repository
public class DoctorDailyReportDao extends MyBatisDao<DoctorDailyReport> {

    public DoctorDailyReport findByFarmIdAndSumAt(Long farmId, Date date) {
        String sumAt = DateUtil.toDateString(date);
        return findByFarmIdAndSumAt(farmId, sumAt);
    }

    public DoctorDailyReport findByFarmIdAndSumAt(Long farmId, String date) {
        return getSqlSession().selectOne(sqlId("findByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", date));
    }

    public void deleteByFarmIdAndSumAt(Long farmId, Date sumAt) {
        deleteByFarmIdAndSumAt(farmId, DateUtil.toDateString(sumAt));
    }

    public void deleteByFarmIdAndSumAt(Long farmId, String sumAt) {
        getSqlSession().delete(sqlId("deleteByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", sumAt));
    }

    public DoctorDailyReportSum findDailyReportSum(Long farmId, Date startAt, Date endAt) {
        return getSqlSession().selectOne(sqlId("findDailyReportSum"), ImmutableMap.of("farmId", farmId, "startAt", startAt, "endAt", endAt));
    }
}
