package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.common.utils.Dates;
import io.terminus.doctor.event.model.DoctorDailyReport;
import org.springframework.stereotype.Repository;

import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 日报Dao类
 * Date: 2017-04-19
 */
@Repository
public class DoctorDailyReportDao extends MyBatisDao<DoctorDailyReport> {

    public DoctorDailyReport findByFarmIdAndSumAt(Long farmId, Date date) {
        date = Dates.startOfDay(date);
        return getSqlSession().selectOne(sqlId("findByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", date));
    }

    public DoctorDailyReport findByFarmIdAndSumAt(Long farmId, String date) {
        return getSqlSession().selectOne(sqlId("findByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", date));
    }

    public void deleteByFarmIdAndSumAt(Long farmId, Date sumAt) {
        sumAt = Dates.startOfDay(sumAt);
        getSqlSession().delete(sqlId("deleteByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", sumAt));
    }
}
