package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorDailyGroup;
import org.springframework.stereotype.Repository;

import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数量每天记录表Dao类
 * Date: 2017-04-17
 */
@Repository
public class DoctorDailyGroupDao extends MyBatisDao<DoctorDailyGroup> {

    /**
     * 删除某一天的猪群统计
     * @param farmId
     * @param date
     */
    public void deleteByFarmIdAndSumAt(Long farmId, Date date) {
        getSqlSession().delete(sqlId("deleteByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", date));
    }

    /**
     * 删除某一天的猪群统计
     * @param date
     */
    public void deleteByFarmIdAndSumAt(Date date) {
        getSqlSession().delete(sqlId("deleteBySumAt"), ImmutableMap.of("sumAt", date));
    }
}
