package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorRangeReport;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报Dao类
 * Date: 2017-04-19
 */
@Repository
public class DoctorRangeReportDao extends MyBatisDao<DoctorRangeReport> {

    /**
     * 删除某一天的报表
     * @param farmId
     * @param type
     * @param sumAt
     */
    public void deleteByFarmIdAndTypeAndSumAt(Long farmId, Integer type, String sumAt) {
        getSqlSession().delete(sqlId("deleteByFarmIdAndTypeAndSumAt"), ImmutableMap.of("farmId", farmId, "type", type, "sumAt", sumAt));
    }

    /**
     * 删除公司月报
     * @param orgId 公司id
     * @param sumAt 月份 yyyy-MM
     */
    public void deleteByOrgIdAndSumAt(Long orgId, String sumAt) {
        sqlSession.delete(sqlId("deleteByOrgIdAndSumAt"), ImmutableMap.of("orgId", orgId, "sumAt", sumAt));
    }

    /**
     * 获取公司月报
     * @param orgId 公司id
     * @param sumAt 月份 yyyy-MM
     */
    public DoctorRangeReport findByOrgIdAndSumAt(Long orgId, String sumAt) {
        return sqlSession.selectOne(sqlId("findByOrgIdAndSumAt"), ImmutableMap.of("orgId", orgId, "sumAt", sumAt));
    }

    /**
     * 查询周报、月报指标
     * @param farmId
     * @param type
     * @param sumAt
     * @return
     */
    public DoctorRangeReport findByRangeReport(Long farmId, Integer type, String sumAt) {
        return getSqlSession().selectOne(sqlId("findRangeReport"), ImmutableMap.of("farmId", farmId, "type", type, "sumAt", sumAt));
    }

    /**
     * 根据统计日期查询猪场的指标数据
     * @see io.terminus.doctor.event.enums.ReportRangeType
     * @param type 类行
     * @param sumAt 统计时间
     * @return 指标数据
     */
    public List<DoctorRangeReport> findFarmBySumAt(Integer type, String sumAt) {
        return getSqlSession().selectList(sqlId("findFarmBySumAt"), ImmutableMap.of("type", type, "sumAt", sumAt));
    }
}
