package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorBoarMonthlyReport;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 公猪生产成绩月报Dao类
 * Date: 2016-09-12
 */
@Repository
public class DoctorBoarMonthlyReportDao extends MyBatisDao<DoctorBoarMonthlyReport> {

    /**
     * 根据统计日期删除公猪月报统计
     * @param sumAt 统计日期
     */
    public void deleteBySumAt(String sumAt) {
        getSqlSession().delete(sqlId("deleteBySumAt"), ImmutableMap.of("sumAt", sumAt));
    }

    public void deleteByFarmIdAndSumAt(Long farmId, String sumAt){
        getSqlSession().delete(sqlId("deleteByFarmIdAndSumAt"), ImmutableMap.of("farmId", farmId, "sumAt", sumAt));
    }

    /**
     * 计算公猪月报数据
     * @param farmId
     * @param startAt
     * @param endAt
     * @return
     */
    public List<DoctorBoarMonthlyReport> constructorDoctorBoarMonthlyReports(Long farmId, Date startAt, Date endAt){
        return getSqlSession().selectList(sqlId("constructorDoctorBoarMonthlyReports"), ImmutableMap.of("farmId", farmId, "startAt", startAt, "endAt", endAt));
    }

    public List<DoctorBoarMonthlyReport> findDoctorBoarMonthlyReports(Long farmId, String sumAt){
        return getSqlSession().selectList(sqlId("findDoctorBoarMonthlyReports"), ImmutableMap.of("farmId", farmId, "sumAt", sumAt));
    }
}
