package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorRangeReport;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报Dao类
 * Date: 2017-04-19
 */
@Repository
public class DoctorRangeReportDao extends MyBatisDao<DoctorRangeReport> {

    /**
     * 删除某一天的报表
     * @param farmId
     * @param type
     * @param sumAt
     */
    public void deleteByFarmIdAndTypeAndSumAt(Long farmId, Integer type, String sumAt) {
        getSqlSession().delete(sqlId("deleteByFarmIdAndTypeAndSumAt"), ImmutableMap.of("farmId", farmId, "type", type, "sumAt", sumAt));
    }
}
