package io.terminus.doctor.event.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorVaccinationPigWarn;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 猪只设置免疫程序统计方式Dao类
 * Date: 2016-06-13
 */
@Repository
public class DoctorVaccinationPigWarnDao extends MyBatisDao<DoctorVaccinationPigWarn> {

}
