package io.terminus.doctor.event.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorEventModifyLog;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: Dao类
 * Date: 2017-04-05
 */
@Repository
public class DoctorEventModifyLogDao extends MyBatisDao<DoctorEventModifyLog> {

}
