package io.terminus.doctor.event.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorRangeReport;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报Dao类
 * Date: 2017-04-19
 */
@Repository
public class DoctorRangeReportDao extends MyBatisDao<DoctorRangeReport> {

    /**
     * 删除某一天的报表
     * @param farmId
     * @param type
     * @param sumAt
     */
    public void deleteByFarmIdAndTypeAndSumAt(Long farmId, Integer type, String sumAt) {
        getSqlSession().delete(sqlId("deleteByFarmIdAndTypeAndSumAt"), ImmutableMap.of("farmId", farmId, "type", type, "sumAt", sumAt));
    }

    /**
     * 查询周报、月报指标
     * @param farmId
     * @param type
     * @param sumAt
     * @return
     */
    public DoctorRangeReport findByRangeReport(Long farmId, Integer type, String sumAt) {
        return getSqlSession().selectOne(sqlId("findRangeReport"), ImmutableMap.of("farmId", farmId, "type", type, "sumAt", sumAt));
    }

    public List<DoctorRangeReport> findBySumAt(Integer type, String sumAt) {
        return getSqlSession().selectList(sqlId("findBySumAt"), ImmutableMap.of("type", type, "sumAt", sumAt));
    }
}
