package io.terminus.doctor.event.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.event.model.DoctorMessageRuleTemplateTrack;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表(历史跟踪)Dao类
 * Date: 2016-06-12
 */
@Repository
public class DoctorMessageRuleTemplateTrackDao extends MyBatisDao<DoctorMessageRuleTemplateTrack> {

}
