package io.terminus.doctor.warehouse.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.warehouse.dto.DoctorWareHouseBasicDto;
import io.terminus.doctor.warehouse.model.DoctorWareHouse;
import io.terminus.doctor.warehouse.model.FeedFormula;

/**
 * Code generated by terminus code gen
 * Desc: 饲料配方表写服务
 * Date: 2016-09-26
 */

public interface FeedFormulaWriteService {

    /**
     * 创建FeedFormula
     * @param feedFormula
     * @return 主键id
     */
    Response<Long> createFeedFormula(FeedFormula feedFormula);

    /**
     * 更新FeedFormula
     * @param feedFormula
     * @return 是否成功
     */
    Response<Boolean> updateFeedFormula(FeedFormula feedFormula);

    /**
     * 根据主键id删除FeedFormula
     * @param feedFormulaId
     * @return 是否成功
     */
    Response<Boolean> deleteFeedFormulaById(Long feedFormulaId);

    Response<Boolean> produceFeedByFormula(DoctorWareHouseBasicDto basicDto, DoctorWareHouse targetHouse, FeedFormula feedFormula,
                                           Long feedUnitId, String feedUnitName, FeedFormula.FeedProduce materialProduce);

    Response<FeedFormula.FeedProduce> produceMaterial(Long materialId, Double produceCount);
}