package io.terminus.doctor.warehouse.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.warehouse.model.MaterialFactory;

/**
 * Code generated by terminus code gen
 * Desc: 物资入库时可选择的厂家写服务
 * Date: 2016-09-29
 */

public interface MaterialFactoryWriteService {

    /**
     * 创建MaterialFactory
     * @param materialFactory
     * @return 主键id
     */
    Response<Long> createMaterialFactory(MaterialFactory materialFactory);

    /**
     * 更新MaterialFactory
     * @param materialFactory
     * @return 是否成功
     */
    Response<Boolean> updateMaterialFactory(MaterialFactory materialFactory);

    /**
     * 根据主键id删除MaterialFactory
     * @param materialFactoryId
     * @return 是否成功
     */
    Response<Boolean> deleteMaterialFactoryById(Long materialFactoryId);
}