package io.terminus.doctor.basic.model;

import io.terminus.common.utils.JsonMapper;
import io.terminus.doctor.basic.dto.DoctorWarehouseSnapshotDto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Builder;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 仓库物资每次出库和入库事件之前的快照Model类
 * Date: 2016-09-21
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class DoctorWarehouseSnapshot implements Serializable {

    private static final long serialVersionUID = 5934588860923527558L;
    private Long id;
    
    /**
     * 表doctor_material_consume_providers的id
     */
    private Long eventId;
    
    /**
     * 事件之前的状态, json, 对应dto是 DoctorWarehouseSnapshotDto
     */
    private String beforeEvent;
    
    private Date createdAt;
    
    private Date updatedAt;

    public DoctorWarehouseSnapshotDto json2Snapshot(){
        return JsonMapper.nonEmptyMapper().fromJson(this.beforeEvent, DoctorWarehouseSnapshotDto.class);
    }
}
