package io.terminus.doctor.basic.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 物资入库时可选择的厂家Model类
 * Date: 2016-09-29
 */
@Data
public class MaterialFactory implements Serializable {
    private static final long serialVersionUID = -285876984040303007L;

    private Long id;
    
    private Long farmId;
    
    private String farmName;
    
    private String factoryName;
    
    private String extra;
    
    private Date createdAt;
    
    private Date updatedAt;
}
