package io.terminus.doctor.msg.service;

import com.google.common.base.Throwables;
import io.terminus.common.model.Response;
import io.terminus.doctor.msg.dao.DoctorMessageDao;
import io.terminus.doctor.msg.model.DoctorMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表读服务实现类
 * Date: 2016-05-30
 * Author: chk@terminus.io
 */
@Slf4j
@Service
public class DoctorMessageReadServiceImpl implements DoctorMessageReadService {

    private final DoctorMessageDao doctorMessageDao;

    @Autowired
    public DoctorMessageReadServiceImpl(DoctorMessageDao doctorMessageDao) {
        this.doctorMessageDao = doctorMessageDao;
    }

    @Override
    public Response<DoctorMessage> findMessageById(Long messageId) {
        try {
            return Response.ok(doctorMessageDao.findById(messageId));
        } catch (Exception e) {
            log.error("find message by id failed, messageId:{}, cause:{}", messageId, Throwables.getStackTraceAsString(e));
            return Response.fail("message.find.fail");
        }
    }
}
