package io.terminus.doctor.msg.service;

import com.google.common.base.Throwables;
import io.terminus.common.model.Response;
import io.terminus.doctor.msg.dao.DoctorMessageRuleTemplateDao;
import io.terminus.doctor.msg.model.DoctorMessageRuleTemplate;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表读服务实现类
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */
@Slf4j
@Service
public class DoctorMessageRuleTemplateReadServiceImpl implements DoctorMessageRuleTemplateReadService {

    private final DoctorMessageRuleTemplateDao doctorMessageRuleTemplateDao;

    @Autowired
    public DoctorMessageRuleTemplateReadServiceImpl(DoctorMessageRuleTemplateDao doctorMessageRuleTemplateDao) {
        this.doctorMessageRuleTemplateDao = doctorMessageRuleTemplateDao;
    }

    @Override
    public Response<DoctorMessageRuleTemplate> findMessageRuleTemplateById(Long messageRuleTemplateId) {
        try {
            return Response.ok(doctorMessageRuleTemplateDao.findById(messageRuleTemplateId));
        } catch (Exception e) {
            log.error("find messageRuleTemplate by id failed, messageRuleTemplateId:{}, cause:{}", messageRuleTemplateId, Throwables.getStackTraceAsString(e));
            return Response.fail("messageRuleTemplate.find.fail");
        }
    }
}
