package io.terminus.doctor.msg.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.experimental.Builder;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表Model类
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DoctorMessage implements Serializable {

    private static final long serialVersionUID = 1684778508002616587L;

    /**
     * 自增主键
     */
    private Long id;

    /**
     * 猪场id
     */
    private Long farmId;

    /**
     * 规则id
     */
    private Long ruleId;

    /**
     * 子账号的角色id
     */
    private Long roleId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 消息规则模板id
     */
    private Long templateId;

    /**
     * 消息模板的名称
     */
    private String templateName;

    /**
     * 消息数据填充模板的名称
     */
    private String messageTemplate;

    /**
     * 消息类型: 0->系统消息, 1->预警消息, 2->警报消息
     * @see DoctorMessageRuleTemplate.Type
     */
    private Integer type;

    /**
     * 消息种类
     */
    private Integer category;

    /**
     * 发送的内容填充数据, json(map). 或系统消息
     */
    private String data;

    /**
     * 发送的内容(模板编译之后)
     */
    private String content;

    /**
     * 消息发送渠道. 0->站内信, 1->短信, 2->邮箱, 3->app推送
     */
    private Integer channel;

    /**
     * app回调url
     */
    private String url;

    /**
     * 状态 1:未发送, 2:已发送, 3:已读,  -1:删除, -2:发送失败
     */
    private Integer status;

    /**
     * 未读消息的数量
     * (数据库没有对应字段)
     */
    private Long noReadCount;

    /**
     * 发送时间
     */
    private Date sendedAt;

    /**
     * 失败原因
     */
    private String failedBy;

    /**
     * 操作人id
     */
    private Long createdBy;

    /**
     * 创建时间
     */
    private Date createdAt;

    /**
     * 更新时间
     */
    private Date updatedAt;

    /**
     * 状态枚举值
     */
    public enum Status {
        NORMAL(1, "未发送"),
        SENDED(2, "已发送"),
        READED(3, "已读"),
        DELETE(-1, "删除"),
        FAILED(-2, "发送失败");

        @Getter
        private Integer value;

        @Getter
        private String describe;

        Status(Integer value, String describe) {
            this.value = value;
            this.describe = describe;
        }
    }
}
