package io.terminus.doctor.msg.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则表Model类
 * Date: 2016-05-30
 * author: chk@terminus.io
 */
@Data
public class DoctorMessageRule implements Serializable {

    private static final long serialVersionUID = 6435946068421083427L;
    private Long id;
    
    /**
     * 消息规则名称
     */
    private String name;
    
    /**
     * 消息类型: 0-&gt;系统消息, 1-&gt;预警消息, 2-&gt;警报消息
     */
    private Integer type;
    
    /**
     * 预警规则类型
     */
    private Integer ruleType;
    
    /**
     * 预警默认值
     */
    private Long ruleValue;
    
    /**
     * 预警默认开始值
     */
    private Long ruleStartValue;
    
    /**
     * 预警默认结束值
     */
    private Long ruleEndValue;
    
    /**
     * 消息规则描述
     */
    private String describe;
    
    /**
     * 状态 1:正常, -1:删除, -2:禁用
     */
    private Integer status;
    
    /**
     * 规则模板名称, 对应parana_message_templates表name字段
     */
    private String templateName;
    
    /**
     * 规则的内容, 针对系统消息
     */
    private String content;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
