package io.terminus.doctor.msg.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表Model类
 * Date: 2016-05-30
 * author: chk@terminus.io
 */
@Data
public class DoctorMessage implements Serializable {

    private static final long serialVersionUID = 1684778508002616587L;

    private Long id;
    
    /**
     * 用户id
     */
    private Long userId;
    
    /**
     * 消息类型, doctor_message_rules表冗余
     */
    private Integer type;
    
    /**
     * 发送的内容
     */
    private String content;
    
    /**
     * 消息发送渠道, 多个以逗号分隔. 0->站内信, 1->短信, 2->邮箱
     */
    private String channel;
    
    /**
     * 状态 1:正常未阅读, 2:正常已阅读, -1:删除, -2:发送失败
     */
    private Integer status;
    
    /**
     * 操作人id
     */
    private Long operatorId;
    
    /**
     * 操作人name
     */
    private String operatorName;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
