package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRuleTemplate;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表写服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleTemplateWriteService {

    /**
     * 创建DoctorMessageRuleTemplate
     * @param messageRuleTemplate
     * @return 主键id
     */
    Response<Long> createMessageRuleTemplate(DoctorMessageRuleTemplate messageRuleTemplate);

    /**
     * 更新DoctorMessageRuleTemplate
     * @param messageRuleTemplate
     * @return 是否成功
     */
    Response<Boolean> updateMessageRuleTemplate(DoctorMessageRuleTemplate messageRuleTemplate);

    /**
     * 根据主键id删除DoctorMessageRuleTemplate
     * @param messageRuleTemplateId
     * @return 是否成功
     */
    Response<Boolean> deleteMessageRuleTemplateById(Long messageRuleTemplateId);
}