package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessage;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表读服务
 * Date: 2016-05-30
 * author: chk@terminus.io
 */

public interface DoctorMessageReadService {

    /**
     * 根据id查询猪场软件消息表
     * @param messageId 主键id
     * @return 猪场软件消息表
     */
    Response<DoctorMessage> findMessageById(Long messageId);
}
