package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRuleTemplate;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表读服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleTemplateReadService {

    /**
     * 根据id查询猪场软件消息规则模板表
     * @param messageRuleTemplateId 主键id
     * @return 猪场软件消息规则模板表
     */
    Response<DoctorMessageRuleTemplate> findMessageRuleTemplateById(Long messageRuleTemplateId);

    /**
     * 根据消息种类获取对应的默认消息模板
     * @param category
     *          @see io.terminus.doctor.msg.enums.Category
     * @return
     */
    Response<List<DoctorMessageRuleTemplate>> findByCategory(Integer category);

    /**
     * 获取所有的预警和警报消息
     * @return
     */
    Response<List<DoctorMessageRuleTemplate>> findAllWarnMessageTpl();

    /**
     * 获取模板列表
     * @param criteria
     * @return
     */
    Response<List<DoctorMessageRuleTemplate>> findTemplatesByCriteria(Map<String, Object> criteria);
}
