package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessage;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表读服务
 * Date: 2016-05-30
 * author: chk@terminus.io
 */

public interface DoctorMessageReadService {

    /**
     * 根据id查询猪场软件消息表
     * @param messageId 主键id
     * @return 猪场软件消息表
     */
    Response<DoctorMessage> findMessageById(Long messageId);

    /**
     * 获取未发送的短信消息
     */
    Response<List<DoctorMessage>> findMsgMessage();

    /**
     * 获取未发送的email消息
     */
    Response<List<DoctorMessage>> findEmailMessage();

    /**
     * 获取未发送的app推送消息
     */
    Response<List<DoctorMessage>> findAppPushMessage();
}
