package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRule;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则表读服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleReadService {

    /**
     * 根据id查询猪场软件消息规则默认配置
     * @param messageRuleId 主键id
     * @return 猪场软件消息规则表
     */
    Response<DoctorMessageRule> findMessageRuleById(Long messageRuleId);

    /**
     * 根据模板id获取与猪场绑定的信息列表
     * @param tplId 模板id
     * @return
     */
    Response<List<DoctorMessageRule>> findMessageRulesByTplId(Long tplId);

    /**
     * 根据模板id获取与猪场绑定的正常状态规则列表
     * @param tplId 模板id
     * @return
     */
    Response<List<DoctorMessageRule>> findNormalMessageRulesByTplId(Long tplId);

    /**
     * 根据猪场id查询
     * @param farmId    猪场id
     * @return
     */
    Response<List<DoctorMessageRule>> findMessageRulesByFarmId(Long farmId);

    /**
     *根据 farmId 和templateName查询
     * @param farmId
     * @param templateName
     * @return
     */
    Response<List<DoctorMessageRule>> findMessageRulesByFarmIdAndTemplateName(Long farmId,String templateName);

    /**
     * 根据天健查询消息规则列表
     * @param criteria
     * @return
     */
    Response<List<DoctorMessageRule>> findMessageRulesByCriteria(Map<String, Object> criteria);

}
