package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRule;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则表读服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleReadService {

    /**
     * 根据id查询猪场软件消息规则默认配置
     * @param messageRuleId 主键id
     * @return 猪场软件消息规则表
     */
    Response<DoctorMessageRule> findMessageRuleById(Long messageRuleId);

}
