package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessage;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表写服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageWriteService {

    /**
     * 创建DoctorMessage
     * @param message
     * @return 主键id
     */
    Response<Long> createMessage(DoctorMessage message);

    /**
     * 更新DoctorMessage
     * @param message
     * @return 是否成功
     */
    Response<Boolean> updateMessage(DoctorMessage message);

    /**
     * 根据主键id删除DoctorMessage
     * @param messageId
     * @return 是否成功
     */
    Response<Boolean> deleteMessageById(Long messageId);
}