package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRule;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则表写服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleWriteService {

    /**
     * 创建DoctorMessageRule
     * @param messageRule
     * @return 主键id
     */
    Response<Long> createMessageRule(DoctorMessageRule messageRule);

    /**
     * 更新DoctorMessageRule
     * @param messageRule
     * @return 是否成功
     */
    Response<Boolean> updateMessageRule(DoctorMessageRule messageRule);

    /**
     * 根据主键id删除DoctorMessageRule
     * @param messageRuleId
     * @return 是否成功
     */
    Response<Boolean> deleteMessageRuleById(Long messageRuleId);
}