package io.terminus.doctor.msg.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.msg.model.DoctorMessageRuleRole;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则与角色表读服务
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */

public interface DoctorMessageRuleRoleReadService {

    /**
     * 根据id查询猪场软件消息规则与角色表
     * @param messageRuleRoleId 主键id
     * @return 猪场软件消息规则与角色表
     */
    Response<DoctorMessageRuleRole> findMessageRuleRoleById(Long messageRuleRoleId);
}
