package io.terminus.doctor.user.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: Model类
 * Date: 2016-05-31
 */
@Data
public class ServiceReviewTrack implements Serializable {
    private static final long serialVersionUID = -6842062354493762461L;

    private Long id;
    
    private Long userId;
    
    private Integer type;
    
    private Integer oldStatus;
    
    private Integer newStatus;
    
    /**
     * 状态变更的原因
     */
    private String reason;
    
    /**
     * 操作人id
     */
    private Long reviewerId;
    
    /**
     * 操作人姓名
     */
    private String reviewerName;
    
    private Date createdAt;
    
    private Date updatedAt;
}
