package io.terminus.doctor.basic.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.basic.model.DoctorWarehouseSnapshot;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 仓库物资每次出库和入库事件之前的快照Dao类
 * Date: 2016-09-21
 */
@Repository
public class DoctorWarehouseSnapshotDao extends MyBatisDao<DoctorWarehouseSnapshot> {

    public DoctorWarehouseSnapshot findByEventId(Long eventId){
        return sqlSession.selectOne(sqlId("findByEventId"), eventId);
    }

    public void deleteByEventId(Long eventId){
        sqlSession.delete(sqlId("deleteByEventId"), eventId);
    }
}
