package io.terminus.doctor.basic.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.basic.model.FeedFormula;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 饲料配方表Dao类, 配方生产的都是饲料, 消耗原料和药品
 * Date: 2016-09-26
 */
@Repository
public class FeedFormulaDao extends MyBatisDao<FeedFormula> {

    /**
     * 查询配方
     * @param feedId 饲料(即物料)的id
     * @param farmId
     * @return
     */
    public FeedFormula findByFeedIdAndFarmId(Long feedId, Long farmId){
        return sqlSession.selectOne(sqlId("findByFeedIdAndFarmId"), ImmutableMap.of("feedId", feedId, "farmId", farmId));
    }
}
