package io.terminus.doctor.basic.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.basic.model.MaterialFactory;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 物资入库时可选择的厂家Dao类
 * Date: 2016-09-29
 */
@Repository
public class MaterialFactoryDao extends MyBatisDao<MaterialFactory> {

    public MaterialFactory findByFarmAndName(Long farmId, String factoryName){
        return sqlSession.selectOne(sqlId("findByFarmAndName"), ImmutableMap.of("farmId", farmId, "factoryName", factoryName));
    }

    public List<MaterialFactory> findByFarmId(Long farmId){
        return sqlSession.selectList(sqlId("findByFarmId"), farmId);
    }
}
