package io.terminus.doctor.user.service;

import com.google.common.base.Throwables;
import com.google.common.collect.Maps;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.PageInfo;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.doctor.common.utils.Params;
import io.terminus.doctor.user.dao.DoctorServiceStatusDao;
import io.terminus.doctor.user.model.DoctorServiceReviewExt;
import io.terminus.doctor.user.model.DoctorServiceStatus;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 用户服务状态表读服务实现类
 * Date: 2016-06-03
 */
@Slf4j
@Service
@RpcProvider
public class DoctorServiceStatusReadServiceImpl implements DoctorServiceStatusReadService {

    private final DoctorServiceStatusDao doctorServiceStatusDao;

    @Autowired
    public DoctorServiceStatusReadServiceImpl(DoctorServiceStatusDao doctorServiceStatusDao) {
        this.doctorServiceStatusDao = doctorServiceStatusDao;
    }

    @Override
    public Response<DoctorServiceStatus> findById(Long id) {
        try {
            return Response.ok(doctorServiceStatusDao.findById(id));
        } catch (Exception e) {
            log.error("find serviceStatus by id failed, id:{}, cause:{}", id, Throwables.getStackTraceAsString(e));
            return Response.fail("serviceStatus.find.fail");
        }
    }

    @Override
    public Response<DoctorServiceStatus> findByUserId(Long userId) {
        try {
            return Response.ok(doctorServiceStatusDao.findByUserId(userId));
        } catch (Exception e) {
            log.error("find serviceStatus by userId failed, userId:{}, cause:{}", userId, Throwables.getStackTraceAsString(e));
            return Response.fail("serviceStatus.find.fail");
        }
    }

    @Override
    public Response<Paging<DoctorServiceReviewExt>> page(
            Long userId, Integer type, String userMobile, String orgName, Integer pageNo, Integer pageSize){
        Map<String, Object> criteria = Maps.newHashMap();
        criteria.put("type", type);
        criteria.put("userId", userId);
        criteria.put("userMobile", userMobile);
        criteria.put("orgName", orgName);
        PageInfo pageInfo = new PageInfo(pageNo, pageSize);
        criteria.putAll(pageInfo.toMap());
        criteria = Params.filterNullOrEmpty(criteria);
        try {
            return Response.ok(doctorServiceStatusDao.pagingExt(criteria));
        } catch (Exception e) {
            log.error("page serviceStatus failed, cause:{}", Throwables.getStackTraceAsString(e));
            return Response.fail("serviceStatus.find.fail");
        }
    }

}
