-- 新的猪群报表 2017-12-12
DROP TABLE if EXISTS doctor_group_dailies;
CREATE TABLE `doctor_group_dailies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `farm_id` bigint(20) NOT NULL COMMENT '猪场id',
  `pig_type` tinyint(4) NOT NULL COMMENT '猪群类型',
  `sum_at` date NOT NULL COMMENT '日期',
  `start` int(11) DEFAULT NULL COMMENT '期初',
  `turn_into` int(11) DEFAULT NULL COMMENT '转入数量',
  `chg_farm_in` int(11) DEFAULT NULL COMMENT '转场转入数量',
  `turn_into_weight` double DEFAULT NULL COMMENT '转入总重',
  `turn_into_age` int(11) DEFAULT NULL COMMENT '转入总日龄',
  `chg_farm` int(11) DEFAULT NULL COMMENT '转场数量',
  `chg_farm_weight` double DEFAULT NULL COMMENT '转场总重',
  `sale` int(11) DEFAULT NULL COMMENT '销售',
  `sale_weight` double DEFAULT NULL COMMENT '销售总重',
  `dead` int(11) DEFAULT NULL COMMENT '死亡',
  `weed_out` int(11) DEFAULT NULL COMMENT '淘汰',
  `other_change` int(11) DEFAULT NULL COMMENT '其他变动减少',
  `to_nursery` int(11) DEFAULT NULL COMMENT '转保育',
  `to_fatten` int(11) DEFAULT NULL COMMENT '转育肥',
  `to_fatten_weight` double DEFAULT NULL COMMENT '转育肥总重',
  `to_houbei` int(11) DEFAULT NULL COMMENT '转后备',
  `to_houbei_weight` double DEFAULT NULL COMMENT '转后备总重',
  `turn_seed` int(11) DEFAULT NULL COMMENT '转种猪',
  `turn_out_weight` double DEFAULT NULL COMMENT '转出总重',
  `end` int(11) DEFAULT NULL COMMENT '期末',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新事件',
  `version` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_groups_farm_id_type_sum_at` (`farm_id`,`pig_type`,`sum_at`),
  KEY `idx_doctor_group_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_group_dailies_sum_at` (`sum_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='猪群相关的指标';

DROP TABLE if EXISTS doctor_pig_dailies;
create table doctor_pig_dailies (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  sum_at date NOT NULL COMMENT '日期（yyyy-MM-dd）',
  farm_id bigint(20) NOT NULL COMMENT '猪场',
  sow_ph_start int(11) DEFAULT NULL COMMENT '配怀母猪期初头数',
  sow_ph_reserve_in int(11) DEFAULT NULL COMMENT '后备转入',
  sow_ph_wean_in int(11) DEFAULT NULL COMMENT '配怀母猪断奶转入',
  sow_ph_entry_in int(11) DEFAULT NULL COMMENT '配怀母猪进场',
  sow_ph_chg_farm_in int(11) DEFAULT NULL COMMENT '转场转入',
  sow_ph_dead int(11) DEFAULT NULL COMMENT '配怀死亡母猪',
  sow_ph_weed_out int(11) DEFAULT NULL COMMENT '配怀淘汰母猪',
  sow_ph_sale int(11) DEFAULT NULL COMMENT '配怀母猪销售',
  sow_ph_chg_farm int(11) DEFAULT NULL COMMENT '配怀母猪转场',
  sow_ph_other_out int(11) DEFAULT NULL COMMENT '配怀母猪其他减少',
  mating_count int(11) DEFAULT NULL COMMENT '配种数',
  preg_positive int(11) DEFAULT NULL COMMENT '妊娠检查阳性头数',
  preg_negative int(11) DEFAULT NULL COMMENT '妊娠检查阴性头数',
  preg_fanqing int(11) DEFAULT NULL COMMENT '妊娠检查返情头数',
  preg_liuchan int(11) DEFAULT NULL COMMENT '妊娠检查流产头数',
  sow_ph_end int(11) DEFAULT NULL COMMENT '配怀母猪期末头数',
  sow_cf_start int(11) DEFAULT NULL COMMENT '产房母猪期初存栏',
  sow_cf_end int(11) DEFAULT NULL COMMENT '产房母猪期末存栏',
  sow_cf_in int(11) DEFAULT NULL COMMENT '产房母猪，从配怀转入',
  sow_cf_in_farm_in int(11) DEFAULT NULL COMMENT '产房母猪其他转入 = 转场转入的数量',
  sow_cf_dead int(11) DEFAULT NULL COMMENT '产房母猪死亡数量',
  sow_cf_weed_out int(11) DEFAULT NULL COMMENT '产房母猪淘汰数量',
  sow_cf_sale int(11) DEFAULT NULL COMMENT '产房母猪销售数量',
  sow_cf_chg_farm int(11) DEFAULT NULL COMMENT '产房母猪转场数量',
  sow_cf_other_out int(11) DEFAULT NULL COMMENT '产房母猪其他减少数量',
  farrow_nest int(11) DEFAULT NULL COMMENT '产房分娩窝数',
  farrow_health int(11) DEFAULT NULL COMMENT '产房产健仔数',
  farrow_weak int(11) DEFAULT NULL COMMENT '产房产弱仔数',
  farrow_dead int(11) DEFAULT NULL COMMENT '产房死胎数',
  farrowjmh int(11) DEFAULT NULL COMMENT '产房黑木畸数',
  farrow_weight double DEFAULT NULL COMMENT '产房窝重之和',
  wean_nest int(11) DEFAULT NULL COMMENT '断奶窝数',
  wean_qualified_count int(11) DEFAULT NULL COMMENT '断奶合格数',
  wean_count int(11) DEFAULT NULL COMMENT '断奶仔猪数',
  wean_day_age double DEFAULT NULL COMMENT '每头猪的断奶日龄之和',
  wean_weight double DEFAULT NULL COMMENT '每一窝的断奶均重之和',
  boar_start int(11) DEFAULT NULL COMMENT '公猪期初存栏',
  boar_in int(11) DEFAULT NULL COMMENT '公猪转入数量',
  boar_dead int(11) DEFAULT NULL COMMENT '公猪死亡数量',
  boar_weed_out int(11) DEFAULT NULL COMMENT '公猪淘汰数量',
  boar_sale int(11) DEFAULT NULL COMMENT '公猪销售数量',
  boar_other_out int(11) DEFAULT NULL COMMENT '公猪其他减少',
  boar_end int(11) DEFAULT NULL COMMENT '公猪期末存栏',
  updated_at date DEFAULT NULL COMMENT '更新日期',
  created_at date DEFAULT NULL COMMENT '创建日期',
  version int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_pigs_farm_id_sum_at` (`farm_id`,`sum_at`),
  KEY `idx_doctor_pig_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_pig_dailies_sum_at` (`sum_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='猪相关报表';