CREATE TABLE `doctor_pig_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `org_id` bigint(20) unsigned DEFAULT NULL COMMENT '公司Id',
  `org_name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `farm_id` bigint(20) unsigned DEFAULT NULL COMMENT '猪场Id',
  `farm_name` varchar(64) DEFAULT NULL COMMENT '猪场名称',
  `pig_id` bigint(20) unsigned DEFAULT NULL COMMENT '猪Id',
  `pig_code` varchar(64) DEFAULT NULL COMMENT '猪Code',
  `is_auto` smallint(6) DEFAULT NULL COMMENT '是否是自动生成事件, 0 不是, 1 是',
  `event_at` date NOT NULL COMMENT '事件时间',
  `type` int(11) DEFAULT NULL COMMENT '事件类型',
  `kind` int(11) DEFAULT NULL COMMENT '事件猪类型， 公猪， 母猪， 仔猪',
  `name` varchar(64) DEFAULT NULL COMMENT '事件名称',
  `desc` varchar(512) DEFAULT NULL COMMENT '事件描述',
  `barn_id` bigint(20) unsigned DEFAULT NULL COMMENT '事件地点',
  `barn_name` varchar(64) DEFAULT NULL COMMENT '地点名称',
  `barn_type` tinyint(4) DEFAULT NULL COMMENT '猪舍类型',
  `rel_event_id` bigint(20) DEFAULT NULL COMMENT '关联事件Id',
  `rel_group_event_id` bigint(20) DEFAULT NULL COMMENT '关联猪群事件id(比如转种猪事件)',
  `rel_pig_event_id` bigint(20) DEFAULT NULL COMMENT '关联猪事件id(比如拼窝事件)',
  `change_type_id` bigint(20) DEFAULT NULL COMMENT '变动类型id',
  `basic_id` bigint(20) DEFAULT NULL COMMENT '基础数据id(流产原因id,疾病id,防疫项目id)',
  `basic_name` varchar(32) DEFAULT NULL COMMENT '基础数据名(流产原因,疾病,防疫)',
  `customer_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `customer_name` varchar(64) DEFAULT NULL COMMENT '客户名',
  `vaccination_id` bigint(20) DEFAULT NULL COMMENT '疫苗',
  `vaccination_name` varchar(32) DEFAULT NULL COMMENT '疫苗名称',
  `price` bigint(20) DEFAULT NULL COMMENT '销售单价(分)',
  `amount` bigint(20) DEFAULT NULL COMMENT '销售总额(分)',
  `quantity` int(11) DEFAULT NULL COMMENT '数量(拼窝数量,被拼窝数量,仔猪变动数量)',
  `weight` double DEFAULT NULL COMMENT '重量(变动重量)',
  `pig_status_before` smallint(6) DEFAULT NULL COMMENT '事件发生之前猪的状态',
  `pig_status_after` smallint(6) DEFAULT NULL COMMENT '事件发生之后猪的状态',
  `parity` int(11) DEFAULT NULL COMMENT '事件发生母猪的胎次），记住是前一个事件是妊娠检查事件',
  `is_impregnation` smallint(6) DEFAULT NULL COMMENT '是否可以进行受胎统计，就是妊娠检查阳性之后这个字段为true 0否1是',
  `is_delivery` smallint(6) DEFAULT NULL COMMENT '是否可以进行分娩，就是分娩事件之后这个字段为true 0否1是',
  `preg_days` int(11) DEFAULT NULL COMMENT '孕期，分娩时候统计',
  `feed_days` int(11) DEFAULT NULL COMMENT '哺乳天数，断奶事件发生统计',
  `preg_check_result` smallint(6) DEFAULT NULL COMMENT '妊娠检查结果，从extra中拆出来',
  `dp_npd` int(11) DEFAULT '0' COMMENT '断奶到配种的非生产天数',
  `pf_npd` int(11) DEFAULT '0' COMMENT '配种到返情非生产天数',
  `pl_npd` int(11) DEFAULT '0' COMMENT '配种到流产非生产天数',
  `ps_npd` int(11) DEFAULT '0' COMMENT '配种到死亡非生产天数',
  `py_npd` int(11) DEFAULT '0' COMMENT '配种到阴性非生产天数',
  `pt_npd` int(11) DEFAULT '0' COMMENT '配种到淘汰非生产天数',
  `jp_npd` int(11) DEFAULT '0' COMMENT '配种到配种非生产天数',
  `npd` int(11) DEFAULT '0' COMMENT '非生产天数 前面的总和',
  `group_id` bigint(20) DEFAULT NULL COMMENT '哺乳状态的母猪关联的猪群id',
  `farrow_weight` double DEFAULT NULL COMMENT '分娩总重(kg)',
  `live_count` int(11) DEFAULT NULL COMMENT '活仔数',
  `health_count` int(11) DEFAULT NULL COMMENT '键仔数',
  `weak_count` int(11) DEFAULT NULL COMMENT '弱仔数',
  `mny_count` int(11) DEFAULT NULL COMMENT '木乃伊数',
  `jx_count` int(11) DEFAULT NULL COMMENT '畸形数',
  `dead_count` int(11) DEFAULT NULL COMMENT '死胎数',
  `black_count` int(11) DEFAULT NULL COMMENT '黑胎数',
  `wean_count` int(11) DEFAULT NULL COMMENT '断奶数',
  `wean_avg_weight` double DEFAULT NULL COMMENT '断奶均重(kg)',
  `current_mating_count` double DEFAULT NULL COMMENT '当前配种次数',
  `check_date` datetime DEFAULT NULL COMMENT '检查时间',
  `matting_date` datetime DEFAULT NULL COMMENT '配种时间',
  `farrowing_date` datetime DEFAULT NULL COMMENT '分娩时间',
  `abortion_date` datetime DEFAULT NULL COMMENT '流产时间',
  `partwean_date` datetime DEFAULT NULL COMMENT '断奶时间',
  `judge_preg_date` date DEFAULT NULL COMMENT '预产期',
  `doctor_mate_type` smallint(6) DEFAULT NULL COMMENT '配种类型',
  `mate_type` tinyint(4) DEFAULT NULL COMMENT '配种类型(人工、自然)',
  `boar_code` varchar(64) DEFAULT NULL COMMENT '配种的公猪',
  `out_id` varchar(128) DEFAULT NULL COMMENT '外部Id',
  `status` tinyint(4) NOT NULL COMMENT '是否有效1：有效，0：正在处理， -1：无效',
  `event_source` tinyint(4) DEFAULT NULL COMMENT '事件来源,1、软件录入,2、excel导入,3、旧场迁移',
  `extra` text COMMENT '参考设计文档',
  `source` tinyint(4) DEFAULT NULL COMMENT '进场来源，1：本场，2：外购',
  `breed_id` bigint(20) DEFAULT NULL COMMENT '品种',
  `breed_name` varchar(32) DEFAULT NULL COMMENT '品种',
  `breed_type_id` bigint(20) DEFAULT NULL COMMENT '品系',
  `breed_type_name` varchar(32) DEFAULT NULL COMMENT '品系',
  `boar_type` tinyint(4) DEFAULT NULL COMMENT '公猪类型,1：活公猪，2：冷冻精液，3：新鲜精液',
  `remark` text COMMENT '备注信息',
  `origin` bigint(20) DEFAULT NULL COMMENT '原值',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人id',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `creator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `updator_id` bigint(20) DEFAULT NULL COMMENT '创建人Id',
  `updator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `doctor_pig_events_farm_id` (`farm_id`),
  KEY `doctor_pig_events_pig_id` (`pig_id`),
  KEY `doctor_pig_events_rel_event_id` (`rel_event_id`),
  KEY `doctor_pig_events_boar_code` (`boar_code`),
  KEY `doctor_pig_events_type` (`type`),
  KEY `doctor_pig_events_parity` (`parity`),
  KEY `idx_doctor_pig_events_rel_group_event_id` (`rel_group_event_id`),
  KEY `idx_doctor_pig_events_rel_pig_event_id` (`rel_pig_event_id`),
  KEY `idx_doctor_pig_events_group_id` (`group_id`),
  KEY `idx_doctor_pig_events_barn_id` (`barn_id`),
  KEY `idx_doctor_pig_events_event_at` (`event_at`),
  KEY `doctor_pig_events_barn_id` (`barn_id`)
) COMMENT='用户设备信息表';


CREATE TABLE `doctor_warehouse_material_apply` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `material_handle_id` bigint(20) NOT NULL COMMENT '物料处理编号',
  `org_id` bigint(20) DEFAULT NULL COMMENT '公司ID',
  `farm_id` bigint(20) DEFAULT NULL COMMENT '猪厂编号',
  `warehouse_id` bigint(20) NOT NULL COMMENT '仓库编号',
  `warehouse_type` smallint(6) NOT NULL COMMENT '仓库类型',
  `warehouse_name` varchar(64) DEFAULT NULL COMMENT '仓库名',
  `pig_barn_id` bigint(20) NOT NULL COMMENT '领用猪舍编号',
  `pig_barn_name` varchar(64) DEFAULT NULL COMMENT '领用猪舍名称',
  `pig_type` smallint(6) DEFAULT NULL COMMENT '猪舍类型',
  `pig_group_id` bigint(20) DEFAULT NULL COMMENT '领用猪群编号',
  `pig_group_name` varchar(64) DEFAULT NULL COMMENT '领用猪群名称',
  `material_id` bigint(20) NOT NULL COMMENT '物料编号',
  `apply_date` datetime DEFAULT NULL COMMENT '领用日期',
  `apply_staff_id` bigint(20) DEFAULT NULL COMMENT '领用人编号',
  `apply_staff_name` varchar(64) DEFAULT NULL COMMENT '领用人',
  `apply_year` smallint(12) NOT NULL COMMENT '领用年',
  `apply_month` tinyint(4) NOT NULL COMMENT '领用月',
  `material_name` varchar(64) DEFAULT NULL COMMENT '物料名称',
  `type` smallint(6) DEFAULT NULL COMMENT '物料类型，易耗品，原料，饲料，药品，饲料',
  `unit` varchar(64) DEFAULT NULL COMMENT '单位',
  `quantity` decimal(23,2) NOT NULL COMMENT '数量',
  `unit_price` bigint(20) NOT NULL COMMENT '单价，单位分',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `apply_type` tinyint(4) NOT NULL COMMENT '领用类型。0猪舍，1猪群，2母猪',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
)  COMMENT='仓库物料领用表';

CREATE TABLE `doctor_orgs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `mobile` varchar(16) DEFAULT NULL COMMENT '手机号码',
  `parent_id` bigint(20) DEFAULT NULL COMMENT '父公司id',
  `type` smallint(4) DEFAULT NULL COMMENT '公司类型',
  `license` varchar(512) DEFAULT NULL COMMENT '营业执照复印件图片地址',
  `out_id` varchar(128) DEFAULT NULL COMMENT '外部id',
  `extra` text COMMENT '附加字段',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
)  COMMENT='公司表';

CREATE TABLE `doctor_report_materials` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `houbei_feed_amount` decimal(12,2) NOT NULL COMMENT '后备饲料金额',
  `houbei_feed_quantity` int(11) NOT NULL COMMENT '后备饲料数量',
  `houbei_material_amount` decimal(12,2) NOT NULL COMMENT '后备原料金额',
  `houbei_material_quantity` int(11) NOT NULL COMMENT '后备原料数量',
  `houbei_vaccination_amount` decimal(12,2) NOT NULL COMMENT '后备疫苗金额',
  `houbei_medicine_amount` decimal(12,2) NOT NULL COMMENT '后备兽药金额',
  `houbei_consume_amount` decimal(12,2) NOT NULL COMMENT '后备消耗品金额',
  `peihuai_feed_amount` decimal(12,2) NOT NULL COMMENT '配怀饲料金额',
  `peihuai_feed_quantity` int(11) NOT NULL COMMENT '配怀饲料数量',
  `peihuai_material_amount` decimal(12,2) NOT NULL COMMENT '配怀原料金额',
  `peihuai_material_quantity` int(11) NOT NULL COMMENT '配怀原料数量',
  `peihuai_vaccination_amount` decimal(12,2) NOT NULL COMMENT '配怀疫苗金额',
  `peihuai_medicine_amount` decimal(12,2) NOT NULL COMMENT '配怀兽药金额',
  `peihuai_consume_amount` decimal(12,2) NOT NULL COMMENT '配怀消耗品金额',
  `sow_feed_amount` decimal(12,2) NOT NULL COMMENT '产房母猪饲料金额',
  `sow_feed_quantity` int(11) NOT NULL COMMENT '产房母猪饲料数量',
  `sow_material_amount` decimal(12,2) NOT NULL COMMENT '产房母猪原料金额',
  `sow_material_quantity` int(11) NOT NULL COMMENT '产房母猪原料数量',
  `sow_vaccination_amount` decimal(12,2) NOT NULL COMMENT '产房母猪疫苗金额',
  `sow_medicine_amount` decimal(12,2) NOT NULL COMMENT '产房母猪兽药金额',
  `sow_consume_amount` decimal(12,2) NOT NULL COMMENT '产房母猪消耗品金额',
  `piglet_feed_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪饲料金额',
  `piglet_feed_quantity` int(11) NOT NULL COMMENT '产房仔猪饲料数量',
  `piglet_material_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪原料金额',
  `piglet_material_quantity` int(11) NOT NULL COMMENT '产房仔猪原料数量',
  `piglet_vaccination_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪疫苗金额',
  `piglet_medicine_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪兽药金额',
  `piglet_consume_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪消耗品金额',
  `baoyu_feed_amount` decimal(12,2) NOT NULL COMMENT '保育饲料金额',
  `baoyu_feed_quantity` int(11) NOT NULL COMMENT '保育饲料数量',
  `baoyu_material_amount` decimal(12,2) NOT NULL COMMENT '保育原料金额',
  `baoyu_material_quantity` int(11) NOT NULL COMMENT '保育原料数量',
  `baoyu_vaccination_amount` decimal(12,2) NOT NULL COMMENT '保育疫苗金额',
  `baoyu_medicine_amount` decimal(12,2) NOT NULL COMMENT '保育兽药金额',
  `baoyu_consume_amount` decimal(12,2) NOT NULL COMMENT '保育消耗品金额',
  `yufei_feed_amount` decimal(12,2) NOT NULL COMMENT '育肥饲料金额',
  `yufei_feed_quantity` int(11) NOT NULL COMMENT '育肥饲料数量',
  `yufei_material_amount` decimal(12,2) NOT NULL COMMENT '育肥原料金额',
  `yufei_material_quantity` int(11) NOT NULL COMMENT '育肥原料数量',
  `yufei_vaccination_amount` decimal(12,2) NOT NULL COMMENT '育肥疫苗金额',
  `yufei_medicine_amount` decimal(12,2) NOT NULL COMMENT '育肥兽药金额',
  `yufei_consume_amount` decimal(12,2) NOT NULL COMMENT '育肥消耗品金额',
  `boar_feed_amount` decimal(12,2) NOT NULL COMMENT '公猪饲料金额',
  `boar_feed_quantity` int(11) NOT NULL COMMENT '公猪饲料数量',
  `boar_material_amount` decimal(12,2) NOT NULL COMMENT '公猪原料金额',
  `boar_material_quantity` int(11) NOT NULL COMMENT '公猪原料数量',
  `boar_vaccination_amount` decimal(12,2) NOT NULL COMMENT '公猪疫苗金额',
  `boar_medicine_amount` decimal(12,2) NOT NULL COMMENT '公猪兽药金额',
  `boar_consume_amount` decimal(12,2) NOT NULL COMMENT '公猪消耗品金额',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_materials_orz_id` (`orz_id`)
)  COMMENT='物料消耗报表';


CREATE TABLE `doctor_report_efficiencies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(8) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `npd` decimal(10,2) DEFAULT NULL COMMENT '非生产天数',
  `birth_per_year` decimal(10,2) DEFAULT NULL COMMENT '年生产胎次',
  `psy` decimal(10,2) DEFAULT NULL COMMENT 'psy',
  `pregnancy` int(11) NOT NULL COMMENT '妊娠期',
  `lactation` int(11) NOT NULL COMMENT '哺乳期',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_efficiencies_orz_id` (`orz_id`)
)  COMMENT='效率报表';
