-- 新的猪群报表 2017-12-12
DROP TABLE if EXISTS doctor_group_dailies;
CREATE TABLE `doctor_group_dailies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `farm_id` bigint(20) NOT NULL COMMENT '猪场id',
  `pig_type` tinyint(4) NOT NULL COMMENT '猪群类型',
  `sum_at` date NOT NULL COMMENT '日期',
  `start` int(11) DEFAULT NULL COMMENT '期初',
  `turn_into` int(11) DEFAULT NULL COMMENT '转入数量',
  `chg_farm_in` int(11) DEFAULT NULL COMMENT '转场转入数量',
  `turn_into_weight` double DEFAULT NULL COMMENT '转入总重',
  `turn_into_age` int(11) DEFAULT NULL COMMENT '转入总日龄',
  `chg_farm` int(11) DEFAULT NULL COMMENT '转场数量',
  `chg_farm_weight` double DEFAULT NULL COMMENT '转场总重',
  `sale` int(11) DEFAULT NULL COMMENT '销售',
  `sale_weight` double DEFAULT NULL COMMENT '销售总重',
  `dead` int(11) DEFAULT NULL COMMENT '死亡',
  `weed_out` int(11) DEFAULT NULL COMMENT '淘汰',
  `other_change` int(11) DEFAULT NULL COMMENT '其他变动减少',
  `to_nursery` int(11) DEFAULT NULL COMMENT '转保育',
  `to_fatten` int(11) DEFAULT NULL COMMENT '转育肥',
  `to_fatten_weight` double DEFAULT NULL COMMENT '转育肥总重',
  `to_houbei` int(11) DEFAULT NULL COMMENT '转后备',
  `to_houbei_weight` double DEFAULT NULL COMMENT '转后备总重',
  `turn_seed` int(11) DEFAULT NULL COMMENT '转种猪',
  `turn_out_weight` double DEFAULT NULL COMMENT '转出总重',
  `end` int(11) DEFAULT NULL COMMENT '期末',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新事件',
  `version` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_groups_farm_id_type_sum_at` (`farm_id`,`pig_type`,`sum_at`),
  KEY `idx_doctor_group_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_group_dailies_sum_at` (`sum_at`)
)  COMMENT='猪群相关的指标';

DROP TABLE if EXISTS doctor_pig_dailies;
create table doctor_pig_dailies (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  sum_at date NOT NULL COMMENT '日期（yyyy-MM-dd）',
  farm_id bigint(20) NOT NULL COMMENT '猪场',
  sow_ph_start int(11) DEFAULT NULL COMMENT '配怀母猪期初头数',
  sow_ph_reserve_in int(11) DEFAULT NULL COMMENT '后备转入',
  sow_ph_wean_in int(11) DEFAULT NULL COMMENT '配怀母猪断奶转入',
  sow_ph_entry_in int(11) DEFAULT NULL COMMENT '配怀母猪进场',
  sow_ph_chg_farm_in int(11) DEFAULT NULL COMMENT '转场转入',
  sow_ph_dead int(11) DEFAULT NULL COMMENT '配怀死亡母猪',
  sow_ph_weed_out int(11) DEFAULT NULL COMMENT '配怀淘汰母猪',
  sow_ph_sale int(11) DEFAULT NULL COMMENT '配怀母猪销售',
  sow_ph_chg_farm int(11) DEFAULT NULL COMMENT '配怀母猪转场',
  sow_ph_other_out int(11) DEFAULT NULL COMMENT '配怀母猪其他减少',
  mate_hb int(11) DEFAULT NULL COMMENT '配后备',
  mate_dn int(11) DEFAULT NULL COMMENT '配断奶',
  mate_fq int(11) DEFAULT NULL COMMENT '配返情',
  mate_lc int(11) DEFAULT NULL COMMENT '配流产',
  mate_yx int(11) DEFAULT NULL COMMENT '配阴性',
  mating_count int(11) DEFAULT NULL COMMENT '配种数',
  preg_positive int(11) DEFAULT NULL COMMENT '妊娠检查阳性头数',
  preg_negative int(11) DEFAULT NULL COMMENT '妊娠检查阴性头数',
  preg_fanqing int(11) DEFAULT NULL COMMENT '妊娠检查返情头数',
  preg_liuchan int(11) DEFAULT NULL COMMENT '妊娠检查流产头数',
  sow_ph_end int(11) DEFAULT NULL COMMENT '配怀母猪期末头数',
  sow_cf_start int(11) DEFAULT NULL COMMENT '产房母猪期初存栏',
  sow_cf_end int(11) DEFAULT NULL COMMENT '产房母猪期末存栏',
  sow_cf_in int(11) DEFAULT NULL COMMENT '产房母猪，从配怀转入',
  sow_cf_in_farm_in int(11) DEFAULT NULL COMMENT '产房母猪其他转入 = 转场转入的数量',
  sow_cf_dead int(11) DEFAULT NULL COMMENT '产房母猪死亡数量',
  sow_cf_weed_out int(11) DEFAULT NULL COMMENT '产房母猪淘汰数量',
  sow_cf_sale int(11) DEFAULT NULL COMMENT '产房母猪销售数量',
  sow_cf_chg_farm int(11) DEFAULT NULL COMMENT '产房母猪转场数量',
  sow_cf_other_out int(11) DEFAULT NULL COMMENT '产房母猪其他减少数量',
  farrow_nest int(11) DEFAULT NULL COMMENT '产房分娩窝数',
  farrow_health int(11) DEFAULT NULL COMMENT '产房产健仔数',
  farrow_weak int(11) DEFAULT NULL COMMENT '产房产弱仔数',
  farrow_dead int(11) DEFAULT NULL COMMENT '产房死胎数',
  farrowjmh int(11) DEFAULT NULL COMMENT '产房黑木畸数',
  farrow_weight double DEFAULT NULL COMMENT '产房窝重之和',
  wean_nest int(11) DEFAULT NULL COMMENT '断奶窝数',
  wean_qualified_count int(11) DEFAULT NULL COMMENT '断奶合格数',
  wean_count int(11) DEFAULT NULL COMMENT '断奶仔猪数',
  wean_day_age double DEFAULT NULL COMMENT '每头猪的断奶日龄之和',
  wean_weight double DEFAULT NULL COMMENT '每一窝的断奶均重之和',
  boar_start int(11) DEFAULT NULL COMMENT '公猪期初存栏',
  boar_in int(11) DEFAULT NULL COMMENT '公猪转入数量',
  boar_dead int(11) DEFAULT NULL COMMENT '公猪死亡数量',
  boar_weed_out int(11) DEFAULT NULL COMMENT '公猪淘汰数量',
  boar_sale int(11) DEFAULT NULL COMMENT '公猪销售数量',
  boar_other_out int(11) DEFAULT NULL COMMENT '公猪其他减少',
  boar_end int(11) DEFAULT NULL COMMENT '公猪期末存栏',
  updated_at date DEFAULT NULL COMMENT '更新日期',
  created_at date DEFAULT NULL COMMENT '创建日期',
  version int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_pigs_farm_id_sum_at` (`farm_id`,`sum_at`),
  KEY `idx_doctor_pig_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_pig_dailies_sum_at` (`sum_at`)
)  COMMENT='猪相关报表';


CREATE TABLE `doctor_farms` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `farm_code` varchar(64) DEFAULT NULL COMMENT '猪场号',
  `org_id` bigint(20) DEFAULT NULL COMMENT '公司id',
  `org_name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `province_id` int(11) DEFAULT NULL COMMENT '所在省id',
  `province_name` varchar(64) DEFAULT NULL COMMENT '所在省',
  `city_id` int(11) DEFAULT NULL COMMENT '所在城市id',
  `city_name` varchar(64) DEFAULT NULL COMMENT '所在城市',
  `district_id` int(11) DEFAULT NULL COMMENT '区id',
  `district_name` varchar(64) DEFAULT NULL COMMENT '区名称',
  `detail_address` varchar(256) DEFAULT NULL COMMENT '区之后的具体地址',
  `out_id` varchar(128) DEFAULT NULL COMMENT '外部id',
  `source` tinyint(4) DEFAULT NULL COMMENT '来源,1:软件录入,2:excel导入,3:旧软件迁移，',
  `extra` text COMMENT '附加字段',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_farms_org_id` (`org_id`)
)  COMMENT='猪场表';

CREATE TABLE `doctor_orgs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `mobile` varchar(16) DEFAULT NULL COMMENT '手机号码',
  `license` varchar(512) DEFAULT NULL COMMENT '营业执照复印件图片地址',
  `out_id` varchar(128) DEFAULT NULL COMMENT '外部id',
  `extra` text COMMENT '附加字段',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '修改时间',
  `parent_id` bigint(20) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
)  COMMENT='公司表';
CREATE TABLE `doctor_pigs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `org_id` bigint(20) unsigned DEFAULT NULL COMMENT '公司Id',
  `org_name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `farm_id` bigint(20) unsigned DEFAULT NULL COMMENT '猪场Id',
  `farm_name` varchar(64) DEFAULT NULL COMMENT '猪场名称',
  `out_id` varchar(128) DEFAULT NULL COMMENT '关联猪外部Id',
  `pig_code` varchar(64) DEFAULT NULL COMMENT '猪编号',
  `pig_type` smallint(6) DEFAULT NULL COMMENT '猪类型(公猪，母猪， 仔猪)',
  `is_removal` smallint(6) DEFAULT '0' COMMENT '是否已离场',
  `pig_father_code` varchar(64) DEFAULT NULL COMMENT '猪父亲Id',
  `pig_mother_code` varchar(64) DEFAULT NULL COMMENT '母猪Id',
  `source` smallint(6) DEFAULT NULL COMMENT '母猪来源',
  `birth_date` datetime DEFAULT NULL COMMENT '母猪生日',
  `birth_weight` double DEFAULT NULL COMMENT '出生重量',
  `in_farm_date` datetime DEFAULT NULL COMMENT '进厂日期',
  `in_farm_day_age` int(11) DEFAULT NULL COMMENT '进厂日龄',
  `init_barn_id` bigint(20) unsigned DEFAULT NULL COMMENT '进厂位置',
  `init_barn_name` varchar(64) DEFAULT NULL COMMENT '进厂位置名称',
  `breed_id` bigint(20) unsigned DEFAULT NULL COMMENT '品种id',
  `breed_name` varchar(64) DEFAULT NULL COMMENT '品种名称',
  `genetic_id` bigint(20) unsigned DEFAULT NULL COMMENT '品系Id',
  `genetic_name` varchar(64) DEFAULT NULL COMMENT '品系名称',
  `boar_type` smallint(6) DEFAULT NULL COMMENT '公猪类型: 1 活公猪, 2 冷冻精液, 3 新鲜精液',
  `extra` text COMMENT '公猪（公猪类型，boar_type）母猪（初始胎次:init_parity, 性别：sex, 左右乳头数量： left_nipple_count, right_nipple_count ）',
  `remark` text COMMENT '标注信息',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `creator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `updator_id` bigint(20) DEFAULT NULL COMMENT '创建人Id',
  `updator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `doctor_pigs_farm_id` (`farm_id`),
  KEY `doctor_pigs_pig_code` (`pig_code`),
  KEY `doctor_pigs_is_removal` (`is_removal`)
)  COMMENT='猪基础信息表';
CREATE TABLE `doctor_pig_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `org_id` bigint(20) unsigned DEFAULT NULL COMMENT '公司Id',
  `org_name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `farm_id` bigint(20) unsigned DEFAULT NULL COMMENT '猪场Id',
  `farm_name` varchar(64) DEFAULT NULL COMMENT '猪场名称',
  `pig_id` bigint(20) unsigned DEFAULT NULL COMMENT '猪Id',
  `pig_code` varchar(64) DEFAULT NULL COMMENT '猪Code',
  `is_auto` smallint(6) DEFAULT NULL COMMENT '是否是自动生成事件, 0 不是, 1 是',
  `event_at` date NOT NULL COMMENT '事件时间',
  `type` int(11) DEFAULT NULL COMMENT '事件类型',
  `kind` int(11) DEFAULT NULL COMMENT '事件猪类型， 公猪， 母猪， 仔猪',
  `name` varchar(64) DEFAULT NULL COMMENT '事件名称',
  `desc` varchar(512) DEFAULT NULL COMMENT '事件描述',
  `barn_id` bigint(20) unsigned DEFAULT NULL COMMENT '事件地点',
  `barn_name` varchar(64) DEFAULT NULL COMMENT '地点名称',
  `barn_type` tinyint(4) DEFAULT NULL COMMENT '猪舍类型',
  `rel_event_id` bigint(20) DEFAULT NULL COMMENT '关联事件Id',
  `rel_group_event_id` bigint(20) DEFAULT NULL COMMENT '关联猪群事件id(比如转种猪事件)',
  `rel_pig_event_id` bigint(20) DEFAULT NULL COMMENT '关联猪事件id(比如拼窝事件)',
  `change_type_id` bigint(20) DEFAULT NULL COMMENT '变动类型id',
  `basic_id` bigint(20) DEFAULT NULL COMMENT '基础数据id(流产原因id,疾病id,防疫项目id)',
  `basic_name` varchar(32) DEFAULT NULL COMMENT '基础数据名(流产原因,疾病,防疫)',
  `customer_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `customer_name` varchar(64) DEFAULT NULL COMMENT '客户名',
  `vaccination_id` bigint(20) DEFAULT NULL COMMENT '疫苗',
  `vaccination_name` varchar(32) DEFAULT NULL COMMENT '疫苗名称',
  `price` bigint(20) DEFAULT NULL COMMENT '销售单价(分)',
  `amount` bigint(20) DEFAULT NULL COMMENT '销售总额(分)',
  `quantity` int(11) DEFAULT NULL COMMENT '数量(拼窝数量,被拼窝数量,仔猪变动数量)',
  `weight` double DEFAULT NULL COMMENT '重量(变动重量)',
  `pig_status_before` smallint(6) DEFAULT NULL COMMENT '事件发生之前猪的状态',
  `pig_status_after` smallint(6) DEFAULT NULL COMMENT '事件发生之后猪的状态',
  `parity` int(11) DEFAULT NULL COMMENT '事件发生母猪的胎次），记住是前一个事件是妊娠检查事件',
  `is_impregnation` smallint(6) DEFAULT NULL COMMENT '是否可以进行受胎统计，就是妊娠检查阳性之后这个字段为true 0否1是',
  `is_delivery` smallint(6) DEFAULT NULL COMMENT '是否可以进行分娩，就是分娩事件之后这个字段为true 0否1是',
  `preg_days` int(11) DEFAULT NULL COMMENT '孕期，分娩时候统计',
  `feed_days` int(11) DEFAULT NULL COMMENT '哺乳天数，断奶事件发生统计',
  `preg_check_result` smallint(6) DEFAULT NULL COMMENT '妊娠检查结果，从extra中拆出来',
  `dp_npd` int(11) DEFAULT '0' COMMENT '断奶到配种的非生产天数',
  `pf_npd` int(11) DEFAULT '0' COMMENT '配种到返情非生产天数',
  `pl_npd` int(11) DEFAULT '0' COMMENT '配种到流产非生产天数',
  `ps_npd` int(11) DEFAULT '0' COMMENT '配种到死亡非生产天数',
  `py_npd` int(11) DEFAULT '0' COMMENT '配种到阴性非生产天数',
  `pt_npd` int(11) DEFAULT '0' COMMENT '配种到淘汰非生产天数',
  `jp_npd` int(11) DEFAULT '0' COMMENT '配种到配种非生产天数',
  `npd` int(11) DEFAULT '0' COMMENT '非生产天数 前面的总和',
  `group_id` bigint(20) DEFAULT NULL COMMENT '哺乳状态的母猪关联的猪群id',
  `farrow_weight` double DEFAULT NULL COMMENT '分娩总重(kg)',
  `live_count` int(11) DEFAULT NULL COMMENT '活仔数',
  `health_count` int(11) DEFAULT NULL COMMENT '键仔数',
  `weak_count` int(11) DEFAULT NULL COMMENT '弱仔数',
  `mny_count` int(11) DEFAULT NULL COMMENT '木乃伊数',
  `jx_count` int(11) DEFAULT NULL COMMENT '畸形数',
  `dead_count` int(11) DEFAULT NULL COMMENT '死胎数',
  `black_count` int(11) DEFAULT NULL COMMENT '黑胎数',
  `wean_count` int(11) DEFAULT NULL COMMENT '断奶数',
  `wean_avg_weight` double DEFAULT NULL COMMENT '断奶均重(kg)',
  `current_mating_count` double DEFAULT NULL COMMENT '当前配种次数',
  `check_date` datetime DEFAULT NULL COMMENT '检查时间',
  `matting_date` datetime DEFAULT NULL COMMENT '配种时间',
  `farrowing_date` datetime DEFAULT NULL COMMENT '分娩时间',
  `abortion_date` datetime DEFAULT NULL COMMENT '流产时间',
  `partwean_date` datetime DEFAULT NULL COMMENT '断奶时间',
  `judge_preg_date` date DEFAULT NULL COMMENT '预产期',
  `doctor_mate_type` smallint(6) DEFAULT NULL COMMENT '配种类型',
  `mate_type` tinyint(4) DEFAULT NULL COMMENT '配种类型(人工、自然)',
  `boar_code` varchar(64) DEFAULT NULL COMMENT '配种的公猪',
  `out_id` varchar(128) DEFAULT NULL COMMENT '外部Id',
  `status` tinyint(4) NOT NULL COMMENT '是否有效1：有效，0：正在处理， -1：无效',
  `event_source` tinyint(4) DEFAULT NULL COMMENT '事件来源,1、软件录入,2、excel导入,3、旧场迁移',
  `extra` text COMMENT '参考设计文档',
  `source` tinyint(4) DEFAULT NULL COMMENT '进场来源，1：本场，2：外购',
  `breed_id` bigint(20) DEFAULT NULL COMMENT '品种',
  `breed_name` varchar(32) DEFAULT NULL COMMENT '品种',
  `breed_type_id` bigint(20) DEFAULT NULL COMMENT '品系',
  `breed_type_name` varchar(32) DEFAULT NULL COMMENT '品系',
  `boar_type` tinyint(4) DEFAULT NULL COMMENT '公猪类型,1：活公猪，2：冷冻精液，3：新鲜精液',
  `remark` text COMMENT '备注信息',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人id',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `creator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `updator_id` bigint(20) DEFAULT NULL COMMENT '创建人Id',
  `updator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `doctor_pig_events_farm_id` (`farm_id`),
  KEY `doctor_pig_events_pig_id` (`pig_id`),
  KEY `doctor_pig_events_rel_event_id` (`rel_event_id`),
  KEY `doctor_pig_events_boar_code` (`boar_code`),
  KEY `doctor_pig_events_type` (`type`),
  KEY `doctor_pig_events_parity` (`parity`),
  KEY `idx_doctor_pig_events_rel_group_event_id` (`rel_group_event_id`),
  KEY `idx_doctor_pig_events_rel_pig_event_id` (`rel_pig_event_id`),
  KEY `idx_doctor_pig_events_group_id` (`group_id`),
  KEY `idx_doctor_pig_events_barn_id` (`barn_id`),
  KEY `idx_doctor_pig_events_event_at` (`event_at`),
  KEY `doctor_pig_events_barn_id` (`barn_id`)
)  COMMENT='用户设备信息表';

CREATE TABLE `doctor_pig_tracks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `farm_id` bigint(20) unsigned NOT NULL COMMENT '猪场Id',
  `pig_id` bigint(20) DEFAULT NULL COMMENT '猪id',
  `pig_type` smallint(6) DEFAULT NULL COMMENT '猪类型(公猪，母猪， 仔猪)',
  `status` smallint(6) DEFAULT NULL COMMENT '猪状态信息',
  `is_removal` smallint(6) DEFAULT '0' COMMENT '是否离场信息',
  `current_barn_id` bigint(20) unsigned DEFAULT NULL COMMENT '当前猪舍Id',
  `current_barn_name` varchar(64) DEFAULT NULL COMMENT '当前猪舍名称',
  `current_barn_type` smallint(6) DEFAULT NULL COMMENT '猪舍类型',
  `weight` double DEFAULT NULL COMMENT '猪重量',
  `group_id` bigint(20) DEFAULT NULL COMMENT '哺乳猪群id(断奶后此id置为null)',
  `farrow_qty` int(11) DEFAULT NULL COMMENT '分娩仔猪数',
  `unwean_qty` int(11) DEFAULT NULL COMMENT '未断奶数量',
  `wean_qty` int(11) DEFAULT NULL COMMENT '断奶数量',
  `farrow_avg_weight` double DEFAULT NULL COMMENT '分娩均重(kg)',
  `wean_avg_weight` double DEFAULT NULL COMMENT '断奶均重(kg)',
  `out_farm_date` datetime DEFAULT NULL COMMENT '猪离场时间',
  `rel_event_ids` text COMMENT '关联事件最近事件',
  `current_event_id` bigint(20) NOT NULL COMMENT '最新的事件ID',
  `extra` text COMMENT '事件修改猪对应信息',
  `extra_message` text COMMENT '每只猪的消息提醒',
  `current_parity` int(11) DEFAULT NULL COMMENT '当前胎次信息',
  `current_mating_count` int(11) DEFAULT '0' COMMENT '当前配种次数',
  `remark` text COMMENT '备注',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `creator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `updator_id` bigint(20) DEFAULT NULL COMMENT '创建人Id',
  `updator_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `doctor_pig_tracks_pig_card_id` (`pig_id`),
  KEY `doctor_pig_tracks_farm_id` (`farm_id`),
  KEY `doctor_pig_tracks_current_barn_id` (`current_barn_id`),
  KEY `doctor_pig_tracks_status` (`status`),
  KEY `doctor_pig_tracks_current_parity` (`current_parity`)
)  COMMENT='猪Track 信息表';


