package io.terminus.doctor.event.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报Model类
 * Date: 2017-04-19
 */
@Data
public class DoctorRangeReport extends DoctorIndicatorReport implements Serializable {
    private static final long serialVersionUID = 5062599644349888732L;

    private Long id;
    
    /**
     * 猪场id
     */
    private Long farmId;
    
    /**
     * 类型
     * @see io.terminus.doctor.event.enums.ReportRangeType
     */
    private Integer type;
    
    /**
     * 统计时间
     */
    private String sumAt;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
