package io.terminus.doctor.event.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 胎次产仔分析月报Model类
 * Date: 2016-09-13
 */
@Data
public class DoctorParityMonthlyReport implements Serializable {
    private static final long serialVersionUID = -6247552860738822754L;

    private Long id;
    
    /**
     * 猪场id
     */
    private Long farmId;
    
    /**
     * 胎次
     */
    private Integer parity;
    
    /**
     * 总窝数
     */
    private Integer nestCount;
    
    /**
     * 占比
     */
    private Double percent;
    
    /**
     * 总产仔
     */
    private Integer farrowAll;
    
    /**
     * 平均产仔
     */
    private Double farrowAvg;
    
    /**
     * 统计时间
     */
    private String sumAt;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
