package io.terminus.doctor.event.model;

import com.google.common.base.Strings;
import io.terminus.doctor.common.utils.JsonMapperUtil;
import io.terminus.doctor.event.dto.DoctorStockStructureDto;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报Model类
 * Date: 2017-04-19
 */
@Data
public class DoctorRangeReport extends DoctorIndicatorReport implements Serializable {
    private static final long serialVersionUID = 5062599644349888732L;

    private Long id;
    
    /**
     * 猪场id
     */
    private Long farmId;
    
    /**
     * 类型
     * @see io.terminus.doctor.event.enums.ReportRangeType
     */
    private Integer type;
    
    /**
     * 统计时间
     */
    private String sumAt;

    /**
     * 开始时间
     */
    private Date sumFrom;

    /**
     * 结算时间
     */
    private Date sumTo;

    /**
     * 胎次、品种分布
     * @see DoctorStockStructureDto
     */
    private String extra;

    private DoctorStockStructureDto stockDistributeDto;

    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;

    public void setExtra(String extra){
        this.extra = extra;
        if(!Strings.isNullOrEmpty(extra)){
            this.stockDistributeDto = JsonMapperUtil.JSON_NON_DEFAULT_MAPPER.fromJson(extra, DoctorStockStructureDto.class);
        }
    }
}
