package io.terminus.doctor.event.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: Model类
 * Date: 2017-04-05
 */
@Data
public class DoctorEventModifyLog implements Serializable {
    private static final long serialVersionUID = 5322975163592270985L;

    private Long id;
    
    /**
     * 猪场ID
     */
    private Long farmId;
    
    /**
     * 猪/猪群id
     */
    private Long businessId;
    
    /**
     * 猪/猪群code
     */
    private String businessCode;
    
    /**
     * 处理的事件类型1：猪事件，2：猪群事件
     * @see io.terminus.doctor.event.model.DoctorEventModifyRequest.TYPE
     */
    private Integer type;
    
    /**
     * 编辑申请id
     */
    private Long modifyRequestId;
    
    /**
     * 修改前事件
     */
    private String fromEvent;
    
    /**
     * 修改后事件
     */
    private String toEvent;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新事件
     */
    private Date updatedAt;
}
