package io.terminus.doctor.event.model;

import lombok.Data;
import lombok.Getter;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;
import java.util.zip.Inflater;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数据校验表Model类
 * Date: 2017-03-25
 */
@Data
public class DoctorGroupInfoCheck implements Serializable {
    private static final long serialVersionUID = -5305154703513714578L;

    private Long id;
    
    /**
     * 猪场id
     */
    private Long farmId;
    
    /**
     * 猪场名称
     */
    private String farmName;
    
    /**
     * 猪群id
     */
    private Long groupId;
    
    /**
     * 猪群code
     */
    private String groupCode;
    
    /**
     * 根据时间算出的猪群数量
     */
    private Integer eventCount;
    
    /**
     * track中的数量
     */
    private Integer trackCount;
    
    /**
     * 日期
     */
    private Date sumAt;
    
    /**
     * 状态，-1：track数据不正确，0：正在处理，1：track数据正确， 2：已处理正确
     */
    private Integer status;
    
    private String extra;
    
    /**
     * 备注
     */
    private String remark;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 创建人id
     */
    private Long creatorId;
    
    /**
     * 创建人name
     */
    private String creatorName;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
    
    /**
     * 更新人id
     */
    private Long updatorId;
    
    /**
     * 更新人name
     */
    private String updatorName;

    public enum DataCheckStatus {
        ERROR(-1, "猪群数量错误"),
        RIGHT(1, "猪群数量正确"),
        MODIFY(2, " 已修复");

        @Getter
        private Integer value;

        @Getter
        private String desc;

        DataCheckStatus(Integer value, String desc){
            this.value = value;
            this.desc = desc;
        }

        public static DataCheckStatus from(Integer value){
            for(DataCheckStatus dataCheckStatus: DataCheckStatus.values()){
                if(Objects.equals(value, dataCheckStatus.getValue())){
                    return dataCheckStatus;
                }
            }
            return null;
        }

    }
}