package io.terminus.doctor.event.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 日报Model类
 * Date: 2017-04-19
 */
@Data
public class DoctorDailyReport extends DoctorBaseReport implements Serializable {
    private static final long serialVersionUID = -1834863070047257695L;

    private Long id;
    
    /**
     * 配怀母猪头数
     */
    private Integer sowPh;
    
    /**
     * 产房母猪头数
     */
    private Integer sowCf;

    /**
     * 创建时间
     */
    private Date createdAt;

    /**
     * 更新时间
     */
    private Date updatedAt;
}
