package io.terminus.doctor.event.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表(历史跟踪)Model类
 * Date: 2016-06-12
 */
@Data
public class DoctorMessageRuleTemplateTrack implements Serializable {
    private static final long serialVersionUID = 8255584037322707328L;

    private Long id;
    
    /**
     * 消息规则模板id
     */
    private Long templateId;
    
    /**
     * 消息规则模板名称
     */
    private String name;
    
    /**
     * 消息类型: 0->系统消息, 1->预警消息, 2->警报消息
     */
    private Integer type;
    
    /**
     * 消息种类
     */
    private Integer category;
    
    /**
     * 规则, 是farm对应的默认值, json值, 类: Rule
     */
    private String ruleValue;
    
    /**
     * 状态 1:正常, -1:删除, -2:禁用
     */
    private Integer status;
    
    /**
     * 规则数据模板名称, 对应parana_message_templates表name字段
     */
    private String messageTemplate;
    
    /**
     * 规则的内容, 针对系统消息
     */
    private String content;
    
    /**
     * 消息生成者(类的简单类名)
     */
    private String producer;
    
    /**
     * 消息规则模板描述
     */
    private String describe;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
    
    /**
     * 修改人id
     */
    private Long updatorId;
    
    /**
     * 修改人name
     */
    private String updatorName;
}
