package io.terminus.doctor.user.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.user.model.DoctorServiceStatus;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 用户服务状态表Dao类
 * Date: 2016-06-03
 */
@Repository
public class DoctorServiceStatusDao extends MyBatisDao<DoctorServiceStatus> {

    public DoctorServiceStatus findByUserId(Long userId){
        return sqlSession.selectOne(sqlId("findByUserId"), userId);
    }

    public boolean updateWithNull(DoctorServiceStatus doctorServiceStatus){
        return sqlSession.update(sqlId("updateWithNull"), doctorServiceStatus) == 1;
    }
}
