package io.terminus.doctor.user.dao;

import com.google.common.collect.ImmutableMap;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.user.model.DoctorServiceReview;
import io.terminus.doctor.user.model.ServiceReviewTrack;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: Dao类
 * Date: 2016-05-31
 */
@Repository
public class ServiceReviewTrackDao extends MyBatisDao<ServiceReviewTrack> {

    public List<ServiceReviewTrack> findByUserId(Long userId){
        return sqlSession.selectList(sqlId("findByUserId"), userId);
    }

    public List<ServiceReviewTrack> findByUserIdAndType(Long userId, DoctorServiceReview.Type type){
        return sqlSession.selectList(sqlId("findByUserId"), ImmutableMap.of("userId", userId, "type", type.getValue()));
    }

    public ServiceReviewTrack findLastByUserIdAndType(Long userId, DoctorServiceReview.Type type){
        return sqlSession.selectOne(sqlId("findLastByUserIdAndType"), ImmutableMap.of("userId", userId, "type", type.getValue()));
    }
}
