package io.terminus.doctor.event.service;

import com.google.common.base.Throwables;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import io.terminus.doctor.event.dao.DoctorDailyGroupDao;
import io.terminus.doctor.event.model.DoctorDailyGroup;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数量每天记录表读服务实现类
 * Date: 2017-04-17
 */
@Slf4j
@Service
@RpcProvider
public class DoctorDailyGroupReadServiceImpl implements DoctorDailyGroupReadService {

    private final DoctorDailyGroupDao doctorDailyGroupDao;

    @Autowired
    public DoctorDailyGroupReadServiceImpl(DoctorDailyGroupDao doctorDailyGroupDao) {
        this.doctorDailyGroupDao = doctorDailyGroupDao;
    }

    @Override
    public Response<DoctorDailyGroup> findDoctorDailyGroupById(Long doctorDailyGroupId) {
        try {
            return Response.ok(doctorDailyGroupDao.findById(doctorDailyGroupId));
        } catch (Exception e) {
            log.error("find doctorDailyGroup by id failed, doctorDailyGroupId:{}, cause:{}", doctorDailyGroupId, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorDailyGroup.find.fail");
        }
    }
}
