package io.terminus.doctor.event.service;

import com.google.common.base.Throwables;
import io.terminus.common.model.Response;
import io.terminus.doctor.event.dao.DoctorEventModifyLogDao;
import io.terminus.doctor.event.model.DoctorEventModifyLog;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 读服务实现类
 * Date: 2017-04-05
 */
@Slf4j
@Service
public class DoctorEventModifyLogReadServiceImpl implements DoctorEventModifyLogReadService {

    private final DoctorEventModifyLogDao doctorEventModifyLogDao;

    @Autowired
    public DoctorEventModifyLogReadServiceImpl(DoctorEventModifyLogDao doctorEventModifyLogDao) {
        this.doctorEventModifyLogDao = doctorEventModifyLogDao;
    }

    @Override
    public Response<DoctorEventModifyLog> findDoctorEventModifyLogById(Long doctorEventModifyLogId) {
        try {
            return Response.ok(doctorEventModifyLogDao.findById(doctorEventModifyLogId));
        } catch (Exception e) {
            log.error("find doctorEventModifyLog by id failed, doctorEventModifyLogId:{}, cause:{}", doctorEventModifyLogId, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorEventModifyLog.find.fail");
        }
    }
}
