package io.terminus.doctor.event.service;

import com.google.common.base.Throwables;
import com.google.common.collect.Lists;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import io.terminus.common.utils.Arguments;
import io.terminus.common.utils.Dates;
import io.terminus.doctor.common.enums.PigType;
import io.terminus.doctor.common.utils.DateUtil;
import io.terminus.doctor.event.dao.DoctorDailyGroupDao;
import io.terminus.doctor.event.dao.DoctorGroupDao;
import io.terminus.doctor.event.dao.DoctorKpiDao;
import io.terminus.doctor.event.model.DoctorDailyGroup;
import io.terminus.doctor.event.model.DoctorGroup;
import lombok.extern.slf4j.Slf4j;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数量每天记录表写服务实现类
 * Date: 2017-04-17
 */
@Slf4j
@Service
@RpcProvider
public class DoctorDailyGroupWriteServiceImpl implements DoctorDailyGroupWriteService {

    private final DoctorDailyGroupDao doctorDailyGroupDao;
    private final DoctorGroupDao doctorGroupDao;
    private final DoctorKpiDao doctorKpiDao;

    @Autowired
    public DoctorDailyGroupWriteServiceImpl(DoctorDailyGroupDao doctorDailyGroupDao, DoctorGroupDao doctorGroupDao, DoctorKpiDao doctorKpiDao) {
        this.doctorDailyGroupDao = doctorDailyGroupDao;
        this.doctorGroupDao = doctorGroupDao;
        this.doctorKpiDao = doctorKpiDao;
    }

    @Override
    public Response<Long> createDoctorDailyGroup(DoctorDailyGroup doctorDailyGroup) {
        try {
            doctorDailyGroupDao.create(doctorDailyGroup);
            return Response.ok(doctorDailyGroup.getId());
        } catch (Exception e) {
            log.error("create doctorDailyGroup failed, doctorDailyGroup:{}, cause:{}", doctorDailyGroup, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorDailyGroup.create.fail");
        }
    }

    @Override
    public Response<Boolean> updateDoctorDailyGroup(DoctorDailyGroup doctorDailyGroup) {
        try {
            return Response.ok(doctorDailyGroupDao.update(doctorDailyGroup));
        } catch (Exception e) {
            log.error("update doctorDailyGroup failed, doctorDailyGroup:{}, cause:{}", doctorDailyGroup, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorDailyGroup.update.fail");
        }
    }

    @Override
    public Response<Boolean> deleteDoctorDailyGroupById(Long doctorDailyGroupId) {
        try {
            return Response.ok(doctorDailyGroupDao.delete(doctorDailyGroupId));
        } catch (Exception e) {
            log.error("delete doctorDailyGroup failed, doctorDailyGroupId:{}, cause:{}", doctorDailyGroupId, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorDailyGroup.delete.fail");
        }
    }

    @Override
    public Response<Boolean> generateYesterdayAndToday(List<Long> farmIds, Date date) {
        try{
            Date yesterday = new DateTime(date).minusDays(1).toDate();
            createDailyGroups(farmIds, yesterday);
            createDailyGroups(farmIds, date);
        }catch(Exception e){
            log.info("generate yesterday and today failed, cause: {}", Throwables.getStackTraceAsString(e));
            return Response.ok(Boolean.FALSE);
        }

        return Response.ok(Boolean.TRUE);
    }

    @Override
    public Response<Boolean> createDailyGroups(List<Long> farmIds, Date date) {
        try{
            doctorDailyGroupDao.deleteByFarmIdAndSumAt(date);
            farmIds.forEach(farmId -> {
                log.info("create group daily start, farmId: {}, date: {}, now is: {}", farmId, DateUtil.toDateString(date), DateUtil.toDateTimeString(new Date()));
                createDailyGroupReport(farmId, date);
            });
        }catch (Exception e){
            log.error("create group daily failed, cause: {}", Throwables.getStackTraceAsString(e));
            return Response.fail("create group daily failed");
        }
        return Response.ok(Boolean.TRUE);
    }

    @Override
    public Response<Boolean> createDailyGroups(Long farmId, Date date) {
        try{
            log.info("create group daily start, farmId: {}, date: {}, now is: {}", farmId, DateUtil.toDateString(date), DateUtil.toDateTimeString(new Date()));
            doctorDailyGroupDao.deleteByFarmIdAndSumAt(farmId, date);
            createDailyGroupReport(farmId, date);
        }catch (Exception e){
            log.error("create group daily failed, cause: {}", Throwables.getStackTraceAsString(e));
            return Response.fail("create group daily failed");
        }
        return Response.ok(Boolean.TRUE);
    }

    @Override
    public Response<Boolean> createDailyGroupsByDateRange(Long farmId, Date fromDate, Date toDate) {
        log.info("create farm(farmId={}) daily group from {} to {} start", farmId, fromDate, toDate);
        try {
            if (Arguments.isNull(fromDate)) {
                fromDate = Dates.startOfDay(new Date());
            }
            if (Arguments.isNull(toDate)) {
                toDate = Dates.startOfDay(new Date());
            }
            while (!fromDate.after(toDate)) {
                log.info("create group daily start, farmId: {}, date: {}, now is: {}", farmId, DateUtil.toDateString(fromDate), DateUtil.toDateTimeString(new Date()));
                doctorDailyGroupDao.deleteByFarmIdAndSumAt(farmId, fromDate);
                createDailyGroupReport(farmId, fromDate);
                fromDate = new DateTime(fromDate).plusDays(1).toDate();
            }
        }catch (Exception e) {
            log.error("create group daily failed, cause: {}", Throwables.getStackTraceAsString(e));
            return Response.fail("create group daily failed");
        }
        return Response.ok(Boolean.TRUE);
    }

    private void createDailyGroupReport(Long farmId, Date date) {
        List<DoctorGroup> groups= doctorGroupDao.findByFarmIdAndDate(farmId, DateUtil.getDateEnd(new DateTime(date)).toDate());
        List<DoctorDailyGroup> dailyGroups = Lists.newArrayList();
        groups.forEach(group -> {
            DoctorDailyGroup doctorDailyGroup = getDoctorDailyGroup(group, date, DateUtil.getDateEnd(new DateTime(date)).toDate());
            dailyGroups.add(doctorDailyGroup);
        });
        if(!Arguments.isNullOrEmpty(dailyGroups)){
            doctorDailyGroupDao.creates(dailyGroups);
        }
    }

    private DoctorDailyGroup getDoctorDailyGroup(DoctorGroup group, Date startAt, Date endAt) {
        Long groupId = group.getId();
        DoctorDailyGroup doctorDailyGroup = new DoctorDailyGroup();
        doctorDailyGroup.setFarmId(group.getFarmId());
        doctorDailyGroup.setGroupId(groupId);
        doctorDailyGroup.setType(group.getPigType());
        doctorDailyGroup.setSumAt(startAt);
        doctorDailyGroup.setStart(doctorKpiDao.realTimeLivetockGroup(groupId, new DateTime(startAt).minusDays(1).toDate()));

        doctorDailyGroup.setInnerIn(doctorKpiDao.getGroupInnerIn(groupId, startAt, endAt));
        doctorDailyGroup.setOuterIn(doctorKpiDao.getGroupOuterIn(groupId, startAt, endAt));
        doctorDailyGroup.setSale(doctorKpiDao.getGroupSale(groupId, startAt, endAt));
        doctorDailyGroup.setDead(doctorKpiDao.getGroupDead(groupId, startAt, endAt));
        doctorDailyGroup.setWeedOut(doctorKpiDao.getGroupWeedOut(groupId, startAt, endAt));
        doctorDailyGroup.setOtherChange(doctorKpiDao.getGroupOtherChange(groupId, startAt, endAt));
        doctorDailyGroup.setChgFarm(doctorKpiDao.getGroupChgFarm(groupId, startAt, endAt));
        doctorDailyGroup.setInnerOut(doctorKpiDao.getGroupInnerOut(groupId, startAt, endAt));
        doctorDailyGroup.setToNursery(0);
        doctorDailyGroup.setToFatten(0);
        doctorDailyGroup.setToHoubei(0);
        doctorDailyGroup.setTurnSeed(0);
        if(Objects.equals(PigType.DELIVER_SOW.getValue(), group.getPigType())){
            doctorDailyGroup.setUnweanCount(doctorKpiDao.getGroupUnWean(groupId, endAt));
            doctorDailyGroup.setWeanCount(doctorKpiDao.getGroupWean(groupId, endAt));
            doctorDailyGroup.setToNursery(doctorKpiDao.getGroupOuterOut(groupId, startAt, endAt));
        }
        if(Objects.equals(PigType.NURSERY_PIGLET.getValue(), group.getPigType())){
            doctorDailyGroup.setToFatten(doctorKpiDao.getNurSeryOuterOut(groupId, PigType.FATTEN_PIG.getValue(), startAt, endAt));
            doctorDailyGroup.setToHoubei(doctorKpiDao.getNurSeryOuterOut(groupId, PigType.RESERVE.getValue(), startAt, endAt));
        }
        if(Objects.equals(PigType.FATTEN_PIG.getValue(), group.getPigType())){
            doctorDailyGroup.setToHoubei(doctorKpiDao.getGroupOuterOut(groupId, startAt, endAt));
        }
        if(Objects.equals(PigType.RESERVE.getValue(), group.getPigType())){
            doctorDailyGroup.setToFatten(doctorKpiDao.getGroupOuterOut(groupId, startAt, endAt));
            doctorDailyGroup.setTurnSeed(doctorKpiDao.getGroupTrunSeed(groupId, startAt, endAt));
        }
        doctorDailyGroup.setEnd(doctorKpiDao.realTimeLivetockGroup(groupId, startAt));
        return doctorDailyGroup;
    }
}
