package io.terminus.doctor.event.service;

import com.google.common.base.Throwables;
import io.terminus.common.model.Response;
import io.terminus.doctor.event.dao.DoctorBoarMonthlyReportDao;
import io.terminus.doctor.event.model.DoctorBoarMonthlyReport;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 公猪生产成绩月报读服务实现类
 * Date: 2016-09-12
 */
@Slf4j
@Service
public class DoctorBoarMonthlyReportReadServiceImpl implements DoctorBoarMonthlyReportReadService {

    private final DoctorBoarMonthlyReportDao doctorBoarMonthlyReportDao;

    @Autowired
    public DoctorBoarMonthlyReportReadServiceImpl(DoctorBoarMonthlyReportDao doctorBoarMonthlyReportDao) {
        this.doctorBoarMonthlyReportDao = doctorBoarMonthlyReportDao;
    }

    @Override
    public Response<DoctorBoarMonthlyReport> findDoctorBoarMonthlyReportById(Long doctorBoarMonthlyReportId) {
        try {
            return Response.ok(doctorBoarMonthlyReportDao.findById(doctorBoarMonthlyReportId));
        } catch (Exception e) {
            log.error("find doctorBoarMonthlyReport by id failed, doctorBoarMonthlyReportId:{}, cause:{}", doctorBoarMonthlyReportId, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorBoarMonthlyReport.find.fail");
        }
    }
}
