package io.terminus.doctor.event.service;

import com.google.common.base.Throwables;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import io.terminus.doctor.event.dao.DoctorParityMonthlyReportDao;
import io.terminus.doctor.event.model.DoctorParityMonthlyReport;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 胎次产仔分析月报读服务实现类
 * Date: 2016-09-13
 */
@Slf4j
@Service
@RpcProvider
public class DoctorParityMonthlyReportReadServiceImpl implements DoctorParityMonthlyReportReadService {

    private final DoctorParityMonthlyReportDao doctorParityMonthlyReportDao;

    @Autowired
    public DoctorParityMonthlyReportReadServiceImpl(DoctorParityMonthlyReportDao doctorParityMonthlyReportDao) {
        this.doctorParityMonthlyReportDao = doctorParityMonthlyReportDao;
    }

    @Override
    public Response<DoctorParityMonthlyReport> findDoctorParityMonthlyReportById(Long doctorParityMonthlyReportId) {
        try {
            return Response.ok(doctorParityMonthlyReportDao.findById(doctorParityMonthlyReportId));
        } catch (Exception e) {
            log.error("find doctorParityMonthlyReport by id failed, doctorParityMonthlyReportId:{}, cause:{}", doctorParityMonthlyReportId, Throwables.getStackTraceAsString(e));
            return Response.fail("doctorParityMonthlyReport.find.fail");
        }
    }
}
