-- Create syntax for TABLE 'doctor_group_dailies'
CREATE TABLE `doctor_group_dailies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `org_id` bigint(20) NOT NULL COMMENT '所属公司id',
  `org_name` varchar(64) NOT NULL COMMENT '所属公司名',
  `farm_id` bigint(20) NOT NULL COMMENT '猪场id',
  `farm_name` varchar(64) NOT NULL COMMENT '所属猪场名',
  `pig_type` tinyint(4) NOT NULL COMMENT '猪群类型',
  `sum_at` date NOT NULL COMMENT '日期',
  `start` int(11) DEFAULT NULL COMMENT '期初',
  `turn_into` int(11) DEFAULT NULL COMMENT '转入数量',
  `turn_into_weight` double DEFAULT NULL COMMENT '转入总重',
  `turn_into_age` int(11) DEFAULT NULL COMMENT '转入总日龄',
  `chg_farm_in_weight` double DEFAULT NULL COMMENT '转场转入重量',
  `chg_farm_in_age` int(11) DEFAULT NULL COMMENT '转场转入日龄',
  `chg_farm_in` int(11) DEFAULT NULL COMMENT '转场转入数量',
  `deliver_hand_turn_into` int(11) DEFAULT NULL COMMENT '产房手动操作转入猪群数量',
  `chg_farm` int(11) DEFAULT NULL COMMENT '转场数量',
  `chg_farm_weight` double DEFAULT NULL COMMENT '转场总重',
  `sale` int(11) DEFAULT NULL COMMENT '销售',
  `sale_weight` double DEFAULT NULL COMMENT '销售总重',
  `dead` int(11) DEFAULT NULL COMMENT '死亡',
  `weed_out` int(11) DEFAULT NULL COMMENT '淘汰',
  `other_change` int(11) DEFAULT NULL COMMENT '其他变动减少',
  `to_nursery` int(11) DEFAULT NULL COMMENT '转保育',
  `to_nursery_weight` double DEFAULT NULL COMMENT '转保育总重',
  `to_fatten` int(11) DEFAULT NULL COMMENT '转育肥',
  `to_fatten_weight` double DEFAULT NULL COMMENT '转育肥总重',
  `to_houbei` int(11) DEFAULT NULL COMMENT '转后备',
  `to_houbei_weight` double DEFAULT NULL COMMENT '转后备总重',
  `turn_seed` int(11) DEFAULT NULL COMMENT '转种猪',
  `turn_out_weight` double DEFAULT NULL COMMENT '转出总重',
  `turn_actual_count` int(11) DEFAULT NULL COMMENT '结束猪群转出实际数量（用于计算保育和育肥转出均重）',
  `turn_actual_weight` double DEFAULT NULL COMMENT '结束猪群转出实际总重量（用于计算保育和育肥转出均重）',
  `turn_actual_age` int(11) DEFAULT NULL COMMENT '结束猪群转出实际总日龄',
  `net_weight_gain` double DEFAULT NULL COMMENT '结束猪群净增重（用于计算保育和育肥料肉比）',
  `deliver_turn_out_age` int(11) DEFAULT NULL COMMENT '产房转出总日龄',
  `end` int(11) DEFAULT NULL COMMENT '期末',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新事件',
  `version` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_groups_farm_id_type_sum_at` (`farm_id`,`pig_type`,`sum_at`),
  KEY `idx_doctor_group_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_group_dailies_sum_at` (`sum_at`)
) ENGINE=InnoDB AUTO_INCREMENT=9057 DEFAULT CHARSET=utf8 COMMENT='猪群相关的指标';

-- Create syntax for TABLE 'doctor_pig_dailies'
CREATE TABLE `doctor_pig_dailies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sum_at` date NOT NULL COMMENT '日期（yyyy-MM-dd）',
  `org_id` bigint(20) NOT NULL COMMENT '所属公司id',
  `org_name` varchar(64) NOT NULL COMMENT '所属公司名',
  `farm_id` bigint(20) NOT NULL COMMENT '猪场',
  `farm_name` varchar(64) NOT NULL COMMENT '猪场名',
  `sow_ph_start` int(11) DEFAULT NULL COMMENT '配怀母猪期初头数',
  `sow_ph_reserve_in` int(11) DEFAULT NULL COMMENT '后备转入',
  `sow_ph_wean_in` int(11) DEFAULT NULL COMMENT '配怀母猪断奶转入',
  `sow_ph_entry_in` int(11) DEFAULT NULL COMMENT '配怀母猪进场',
  `sow_ph_chg_farm_in` int(11) DEFAULT NULL COMMENT '转场转入',
  `sow_ph_dead` int(11) DEFAULT NULL COMMENT '配怀死亡母猪',
  `sow_ph_weed_out` int(11) DEFAULT NULL COMMENT '配怀淘汰母猪',
  `sow_ph_sale` int(11) DEFAULT NULL COMMENT '配怀母猪销售',
  `sow_ph_chg_farm` int(11) DEFAULT NULL COMMENT '配怀母猪转场',
  `sow_ph_other_out` int(11) DEFAULT NULL COMMENT '配怀母猪其他减少',
  `mate_hb` int(11) DEFAULT NULL COMMENT '配后备',
  `mate_dn` int(11) DEFAULT NULL COMMENT '配断奶',
  `mate_fq` int(11) DEFAULT NULL COMMENT '配返情',
  `mate_lc` int(11) DEFAULT NULL COMMENT '配流产',
  `mate_yx` int(11) DEFAULT NULL COMMENT '配阴性',
  `mating_count` int(11) DEFAULT NULL COMMENT '配种数',
  `sow_ph_mating` int(11) DEFAULT NULL COMMENT '配怀舍配种母猪数',
  `sow_ph_konghuai` int(11) DEFAULT NULL COMMENT '配怀空怀母猪数',
  `sow_ph_pregnant` int(11) DEFAULT NULL COMMENT '配怀怀孕母猪数',
  `preg_positive` int(11) DEFAULT NULL COMMENT '妊娠检查阳性头数',
  `preg_negative` int(11) DEFAULT NULL COMMENT '妊娠检查阴性头数',
  `preg_fanqing` int(11) DEFAULT NULL COMMENT '妊娠检查返情头数',
  `preg_liuchan` int(11) DEFAULT NULL COMMENT '妊娠检查流产头数',
  `wean_mate` int(11) DEFAULT NULL COMMENT '断奶母猪7日配种数',
  `wean_dead_weed_out` int(11) DEFAULT NULL COMMENT '断奶母猪7日死淘数',
  `sow_ph_end` int(11) DEFAULT NULL COMMENT '配怀母猪期末头数',
  `sow_cf_start` int(11) DEFAULT NULL COMMENT '产房母猪期初存栏',
  `sow_cf_end` int(11) DEFAULT NULL COMMENT '产房母猪期末存栏',
  `sow_cf_in` int(11) DEFAULT NULL COMMENT '产房母猪，从配怀转入',
  `sow_cf_in_farm_in` int(11) DEFAULT NULL COMMENT '产房母猪其他转入 = 转场转入的数量',
  `sow_cf_dead` int(11) DEFAULT NULL COMMENT '产房母猪死亡数量',
  `sow_cf_weed_out` int(11) DEFAULT NULL COMMENT '产房母猪淘汰数量',
  `sow_cf_sale` int(11) DEFAULT NULL COMMENT '产房母猪销售数量',
  `sow_cf_chg_farm` int(11) DEFAULT NULL COMMENT '产房母猪转场数量',
  `sow_cf_other_out` int(11) DEFAULT NULL COMMENT '产房母猪其他减少数量',
  `early_mating` int(11) DEFAULT NULL COMMENT '前期配种数量',
  `early_farrow_nest` int(11) DEFAULT NULL COMMENT '产房前期分娩窝数',
  `later_nest` int(11) DEFAULT NULL COMMENT '后期分娩窝数',
  `farrow_nest` int(11) DEFAULT NULL COMMENT '产房分娩窝数',
  `farrow_live` int(11) DEFAULT NULL COMMENT '产房产活仔数',
  `farrow_health` int(11) DEFAULT NULL COMMENT '产房产健仔数',
  `farrow_weak` int(11) DEFAULT NULL COMMENT '产房产弱仔数',
  `farrow_dead` int(11) DEFAULT NULL COMMENT '产房死胎数',
  `farrowjmh` int(11) DEFAULT NULL COMMENT '产房黑木畸数',
  `farrow_weight` double DEFAULT NULL COMMENT '产房窝重之和',
  `wean_nest` int(11) DEFAULT NULL COMMENT '断奶窝数',
  `wean_qualified_count` int(11) DEFAULT NULL COMMENT '断奶合格数',
  `wean_count` int(11) DEFAULT NULL COMMENT '断奶仔猪数',
  `wean_day_age` double DEFAULT NULL COMMENT '每头猪的断奶日龄之和',
  `wean_weight` double DEFAULT NULL COMMENT '每一窝的断奶均重之和',
  `boar_start` int(11) DEFAULT NULL COMMENT '公猪期初存栏',
  `boar_in` int(11) DEFAULT NULL COMMENT '公猪转入数量',
  `boar_chg_farm_in` int(11) DEFAULT NULL COMMENT '公猪转场转入数量',
  `boar_dead` int(11) DEFAULT NULL COMMENT '公猪死亡数量',
  `boar_weed_out` int(11) DEFAULT NULL COMMENT '公猪淘汰数量',
  `boar_sale` int(11) DEFAULT NULL COMMENT '公猪销售数量',
  `boar_other_out` int(11) DEFAULT NULL COMMENT '公猪其他减少',
  `boar_end` int(11) DEFAULT NULL COMMENT '公猪期末存栏',
  `updated_at` datetime DEFAULT NULL COMMENT '更新日期',
  `sow_not_mating_count` int(11) DEFAULT NULL COMMENT '进场未配种的母猪数',
  `created_at` datetime DEFAULT NULL COMMENT '创建日期',
  `version` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doctor_daily_pigs_farm_id_sum_at` (`farm_id`,`sum_at`),
  KEY `idx_doctor_pig_dailies_farm_id` (`farm_id`),
  KEY `idx_doctor_pig_dailies_sum_at` (`sum_at`),
  KEY `idx_doctor_pig_dailies_org_id` (`org_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13984 DEFAULT CHARSET=utf8 COMMENT='猪相关报表';


-- Create syntax for TABLE 'doctor_report_boars'
CREATE TABLE `doctor_report_boars` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `turn_into` int(11) NOT NULL COMMENT '转入数量',
  `dead` varchar(512) NOT NULL DEFAULT '' COMMENT '死亡数量',
  `weed_out` varchar(512) NOT NULL DEFAULT '' COMMENT '淘汰数量',
  `sale` varchar(512) NOT NULL COMMENT '销售数量',
  `other_change` int(11) NOT NULL COMMENT '其他减少',
  `daily_pig_count` double(12,2) NOT NULL COMMENT ' 日均存栏',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_boars_orzId` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=71596 DEFAULT CHARSET=utf8 COMMENT='公猪报表';

-- Create syntax for TABLE 'doctor_report_delivers'
CREATE TABLE `doctor_report_delivers` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) DEFAULT NULL COMMENT '期初存栏',
  `end` int(11) DEFAULT NULL COMMENT '期末存栏',
  `sow_cf_in` int(11) DEFAULT NULL COMMENT '配怀转入',
  `other_in` int(11) DEFAULT NULL COMMENT '其他转入',
  `dead` int(11) DEFAULT NULL COMMENT '死亡数量',
  `weed_out` int(11) DEFAULT NULL COMMENT '淘汰数量',
  `sale` int(11) DEFAULT NULL COMMENT '销售数量',
  `chg_farm_out` int(11) DEFAULT NULL COMMENT '转场数量',
  `sow_ph_wean_out` varchar(512) DEFAULT '' COMMENT '断奶转出',
  `other_change` int(11) DEFAULT NULL COMMENT '其他减少',
  `early_mating` int(11) DEFAULT NULL COMMENT '前期配种数量',
  `early_nest` int(11) DEFAULT NULL COMMENT '前期分娩窝数',
  `early_nest_rate` double(14,4) DEFAULT NULL COMMENT ' 前推分娩率',
  `later_nest` int(11) DEFAULT NULL COMMENT '后期分娩窝数',
  `later_nest_rate` double(14,4) DEFAULT NULL COMMENT ' 后推分娩率',
  `farrow_nest` varchar(512) DEFAULT '' COMMENT '分娩窝数',
  `farrow_all` int(11) DEFAULT NULL COMMENT '产仔总数',
  `farrow_living` int(11) DEFAULT NULL COMMENT '产活仔数',
  `farrow_health` int(11) DEFAULT NULL COMMENT '产健仔数',
  `farrow_weak` int(11) DEFAULT NULL COMMENT '产弱仔数',
  `farrow_dead` int(11) DEFAULT NULL COMMENT '死胎数',
  `farrow_jmh` int(11) DEFAULT NULL COMMENT '黑木畸数',
  `piglet_count_per_farrow` double(12,2) DEFAULT NULL COMMENT ' 窝均产仔数',
  `piglet_living_count_per_farrow` double(12,2) DEFAULT NULL COMMENT ' 窝均活仔数',
  `piglet_health_count_per_farrow` double(12,2) DEFAULT NULL COMMENT ' 窝均健仔数',
  `piglet_weak_count_per_farrow` double(12,2) DEFAULT NULL COMMENT ' 窝均弱仔数',
  `avg_weight_per_farrow` double(13,3) DEFAULT NULL COMMENT ' 平均窝重',
  `first_born_weight` double(13,3) DEFAULT NULL COMMENT ' 初生重',
  `piglet_start` int(11) DEFAULT NULL COMMENT '期初存栏（仔猪）',
  `piglet_other_in` int(11) DEFAULT NULL COMMENT '其他转入（仔猪）',
  `piglet_chg_farm_out` int(11) DEFAULT NULL COMMENT '转场数量（仔猪）',
  `piglet_chg_farm_out_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转场均重（仔猪）',
  `to_nursery` varchar(512) DEFAULT '' COMMENT '转保育数',
  `to_nursery_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转保育数均重',
  `piglet_dead` int(11) DEFAULT NULL COMMENT '死亡数量（仔猪）',
  `piglet_weed_out` int(11) DEFAULT NULL COMMENT '淘汰数量（仔猪）',
  `piglet_other_change` int(11) DEFAULT NULL COMMENT '其他减少（仔猪）',
  `piglet_dead_weed_out_rate` double(14,4) DEFAULT NULL COMMENT ' 死淘率（仔猪）',
  `piglet_living_rate` double(14,4) DEFAULT NULL COMMENT ' 成活率（仔猪）',
  `wean_nest` varchar(512) DEFAULT '' COMMENT '断奶窝数',
  `wean_count` int(11) DEFAULT NULL COMMENT '断奶仔猪数',
  `wean_qualified_count` int(11) DEFAULT NULL COMMENT '断奶合格数',
  `wean_count_per_farrow` double(12,2) DEFAULT NULL COMMENT ' 窝均断奶数',
  `wean_day_age` int(11) DEFAULT NULL COMMENT '断奶日龄',
  `wean_weight_per_farrow` double(13,3) DEFAULT NULL COMMENT ' 断奶均重',
  `turn_out_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 产房转出均重',
  `turn_out_day` int(11) DEFAULT NULL COMMENT '产房转出日龄',
  `turn_out_avg_weight_28` double(13,3) DEFAULT NULL COMMENT ' 产房转出均重（28日龄（4周龄重））',
  `piglet_sale` varchar(512) DEFAULT '' COMMENT '销售数量（仔猪）',
  `piglet_sale_ave_weight` double(13,3) DEFAULT NULL COMMENT ' 销售均量（仔猪）',
  `piglet_end` int(11) DEFAULT NULL COMMENT '期末存栏（仔猪）',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_delivers_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=87159 DEFAULT CHARSET=utf8 COMMENT='产房报表';

-- Create syntax for TABLE 'doctor_report_efficiencies'
CREATE TABLE `doctor_report_efficiencies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(8) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `npd` int(11) DEFAULT NULL COMMENT '非生产天数',
  `birth_per_year` int(11) DEFAULT NULL COMMENT '年生产胎次',
  `psy` int(11) DEFAULT NULL COMMENT 'psy',
  `pregnancy` int(11) NOT NULL COMMENT '妊娠期',
  `lactation` int(11) NOT NULL COMMENT '哺乳期',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_efficiencies_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3860 DEFAULT CHARSET=utf8 COMMENT='效率报表';

-- Create syntax for TABLE 'doctor_report_fattens'
CREATE TABLE `doctor_report_fattens` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `turn_into` varchar(512) NOT NULL DEFAULT '' COMMENT '转入数量',
  `turn_into_age` int(11) NOT NULL COMMENT '转入日龄',
  `turn_into_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转入均重',
  `sale` varchar(512) NOT NULL COMMENT '销售数量',
  `sale_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 销售均重',
  `to_houbei` varchar(512) NOT NULL DEFAULT '' COMMENT '转后备数量',
  `to_houbei_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转后备均重',
  `chg_farm_out` varchar(512) NOT NULL DEFAULT '' COMMENT '转场数量',
  `chg_farm_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转场均重',
  `dead` varchar(512) NOT NULL DEFAULT '' COMMENT '死亡数量',
  `weed_out` varchar(512) NOT NULL DEFAULT '' COMMENT '淘汰数量',
  `other_change` varchar(512) NOT NULL DEFAULT '' COMMENT '其他减少',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  `daily_pig_count` double(12,2) DEFAULT NULL COMMENT ' 日均存栏',
  `out_avg_weight_180` double(13,3) DEFAULT NULL COMMENT ' 育肥出栏均重（180日龄（26周龄重））',
  `dead_weed_out_rate` double(14,4) DEFAULT NULL COMMENT ' 死淘率',
  `living_rate` double(14,4) DEFAULT NULL COMMENT ' 成活率',
  `feed_meat_rate` double(12,2) DEFAULT NULL COMMENT ' 料肉比',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_fattens_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=67323 DEFAULT CHARSET=utf8 COMMENT='育肥报表';

-- Create syntax for TABLE 'doctor_report_materials'
CREATE TABLE `doctor_report_materials` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `houbei_feed_amount` decimal(12,2) NOT NULL COMMENT '后备饲料金额',
  `houbei_feed_quantity` int(11) NOT NULL COMMENT '后备饲料数量',
  `houbei_material_amount` decimal(12,2) NOT NULL COMMENT '后备原料金额',
  `houbei_material_quantity` int(11) NOT NULL COMMENT '后备原料数量',
  `houbei_vaccination_amount` decimal(12,2) NOT NULL COMMENT '后备疫苗金额',
  `houbei_medicine_amount` decimal(12,2) NOT NULL COMMENT '后备兽药金额',
  `houbei_consume_amount` decimal(12,2) NOT NULL COMMENT '后备消耗品金额',
  `peihuai_feed_amount` decimal(12,2) NOT NULL COMMENT '配怀饲料金额',
  `peihuai_feed_quantity` int(11) NOT NULL COMMENT '配怀饲料数量',
  `peihuai_material_amount` decimal(12,2) NOT NULL COMMENT '配怀原料金额',
  `peihuai_material_quantity` int(11) NOT NULL COMMENT '配怀原料数量',
  `peihuai_vaccination_amount` decimal(12,2) NOT NULL COMMENT '配怀疫苗金额',
  `peihuai_medicine_amount` decimal(12,2) NOT NULL COMMENT '配怀兽药金额',
  `peihuai_consume_amount` decimal(12,2) NOT NULL COMMENT '配怀消耗品金额',
  `sow_feed_amount` decimal(12,2) NOT NULL COMMENT '产房母猪饲料金额',
  `sow_feed_quantity` int(11) NOT NULL COMMENT '产房母猪饲料数量',
  `sow_material_amount` decimal(12,2) NOT NULL COMMENT '产房母猪原料金额',
  `sow_material_quantity` int(11) NOT NULL COMMENT '产房母猪原料数量',
  `sow_vaccination_amount` decimal(12,2) NOT NULL COMMENT '产房母猪疫苗金额',
  `sow_medicine_amount` decimal(12,2) NOT NULL COMMENT '产房母猪兽药金额',
  `sow_consume_amount` decimal(12,2) NOT NULL COMMENT '产房母猪消耗品金额',
  `piglet_feed_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪饲料金额',
  `piglet_feed_quantity` int(11) NOT NULL COMMENT '产房仔猪饲料数量',
  `piglet_material_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪原料金额',
  `piglet_material_quantity` int(11) NOT NULL COMMENT '产房仔猪原料数量',
  `piglet_vaccination_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪疫苗金额',
  `piglet_medicine_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪兽药金额',
  `piglet_consume_amount` decimal(12,2) NOT NULL COMMENT '产房仔猪消耗品金额',
  `baoyu_feed_amount` decimal(12,2) NOT NULL COMMENT '保育饲料金额',
  `baoyu_feed_quantity` int(11) NOT NULL COMMENT '保育饲料数量',
  `baoyu_material_amount` decimal(12,2) NOT NULL COMMENT '保育原料金额',
  `baoyu_material_quantity` int(11) NOT NULL COMMENT '保育原料数量',
  `baoyu_vaccination_amount` decimal(12,2) NOT NULL COMMENT '保育疫苗金额',
  `baoyu_medicine_amount` decimal(12,2) NOT NULL COMMENT '保育兽药金额',
  `baoyu_consume_amount` decimal(12,2) NOT NULL COMMENT '保育消耗品金额',
  `yufei_feed_amount` decimal(12,2) NOT NULL COMMENT '育肥饲料金额',
  `yufei_feed_quantity` int(11) NOT NULL COMMENT '育肥饲料数量',
  `yufei_material_amount` decimal(12,2) NOT NULL COMMENT '育肥原料金额',
  `yufei_material_quantity` int(11) NOT NULL COMMENT '育肥原料数量',
  `yufei_vaccination_amount` decimal(12,2) NOT NULL COMMENT '育肥疫苗金额',
  `yufei_medicine_amount` decimal(12,2) NOT NULL COMMENT '育肥兽药金额',
  `yufei_consume_amount` decimal(12,2) NOT NULL COMMENT '育肥消耗品金额',
  `boar_feed_amount` decimal(12,2) NOT NULL COMMENT '公猪饲料金额',
  `boar_feed_quantity` int(11) NOT NULL COMMENT '公猪饲料数量',
  `boar_material_amount` decimal(12,2) NOT NULL COMMENT '公猪原料金额',
  `boar_material_quantity` int(11) NOT NULL COMMENT '公猪原料数量',
  `boar_vaccination_amount` decimal(12,2) NOT NULL COMMENT '公猪疫苗金额',
  `boar_medicine_amount` decimal(12,2) NOT NULL COMMENT '公猪兽药金额',
  `boar_consume_amount` decimal(12,2) NOT NULL COMMENT '公猪消耗品金额',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_materials_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3429 DEFAULT CHARSET=utf8 COMMENT='物料消耗报表';

-- Create syntax for TABLE 'doctor_report_matings'
CREATE TABLE `doctor_report_matings` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `houbei_in` int(11) NOT NULL COMMENT '后备转入',
  `sow_ph_wean_in` varchar(512) NOT NULL DEFAULT '' COMMENT '断奶转入',
  `other_in` int(11) NOT NULL COMMENT '其他转入',
  `dead` int(11) NOT NULL COMMENT '死亡数量',
  `weed_out` int(11) NOT NULL COMMENT '淘汰数量',
  `sale` int(11) NOT NULL COMMENT '销售数量',
  `chg_farm_out` int(11) NOT NULL COMMENT '转场数量',
  `other_change` int(11) NOT NULL COMMENT '其他减少',
  `mating_count` int(11) NOT NULL COMMENT '配种数量',
  `mating_sow_count` int(11) NOT NULL COMMENT '已配种母猪数',
  `pregnancy_sow_count` int(11) NOT NULL COMMENT '怀孕母猪数量',
  `no_pregnancy_sow_count` int(11) NOT NULL COMMENT '空怀母猪数量',
  `preg_positive` varchar(512) NOT NULL DEFAULT '' COMMENT '妊检阳性数量',
  `preg_negative` varchar(512) NOT NULL DEFAULT '' COMMENT '妊检阴性数量',
  `preg_fanqing` varchar(512) NOT NULL DEFAULT '' COMMENT '妊检返情数量',
  `preg_liuchan` varchar(512) NOT NULL DEFAULT '' COMMENT '流产数量',
  `mating_rate` double(14,4) DEFAULT NULL COMMENT ' 断奶7日配种率',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_matings_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=41713 DEFAULT CHARSET=utf8 COMMENT='配怀报表';

-- Create syntax for TABLE 'doctor_report_nurseries'
CREATE TABLE `doctor_report_nurseries` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `turn_into` varchar(512) NOT NULL DEFAULT '' COMMENT '转入数量',
  `turn_into_age` int(11) NOT NULL COMMENT '转入日龄',
  `turn_into_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转入均重',
  `sale` varchar(512) NOT NULL COMMENT '销售数量',
  `sale_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 销售均重',
  `to_fatten` varchar(512) NOT NULL DEFAULT '' COMMENT '转育肥数量',
  `to_fatten_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转育肥数均重',
  `to_houbei` varchar(512) NOT NULL DEFAULT '' COMMENT '转后备数量',
  `to_houbei_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转后备均重',
  `chg_farm_out` varchar(512) NOT NULL DEFAULT '' COMMENT '转场数量',
  `chg_farm_avg_weight` double(13,3) DEFAULT NULL COMMENT ' 转场均重',
  `dead` varchar(512) NOT NULL DEFAULT '' COMMENT '死亡数量',
  `weed_out` varchar(512) NOT NULL DEFAULT '' COMMENT '淘汰数量',
  `other_change` varchar(512) NOT NULL DEFAULT '' COMMENT '其他减少',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  `daily_pig_count` double(12,2) DEFAULT NULL COMMENT ' 日均存栏',
  `out_avg_weight_70` double(13,3) DEFAULT NULL COMMENT ' 保育转出均重（70日龄（10周龄重））',
  `dead_weed_out_rate` double(14,4) DEFAULT NULL COMMENT ' 死淘率',
  `living_rate` double(14,4) DEFAULT NULL COMMENT ' 保育成活率',
  `feed_meat_rate` double(12,2) DEFAULT NULL COMMENT ' 料肉比',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_nurseries_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=67300 DEFAULT CHARSET=utf8 COMMENT='保育报表';

-- Create syntax for TABLE 'doctor_report_resevers'
CREATE TABLE `doctor_report_resevers` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `turn_into` varchar(512) NOT NULL DEFAULT '' COMMENT '转入数量',
  `turn_seed` varchar(512) NOT NULL DEFAULT '' COMMENT '转种猪数量',
  `dead` varchar(512) NOT NULL DEFAULT '' COMMENT '死亡数量',
  `weed_out` varchar(512) NOT NULL DEFAULT '' COMMENT '淘汰数量',
  `dead_weed_out_rate` double(14,4) DEFAULT NULL COMMENT ' 死淘率',
  `to_fatten` varchar(512) NOT NULL DEFAULT '' COMMENT '转育肥数量',
  `sale` varchar(512) NOT NULL COMMENT '销售数量',
  `chg_farm_out` varchar(512) NOT NULL DEFAULT '' COMMENT '转场数量',
  `other_change` varchar(512) NOT NULL DEFAULT '' COMMENT '其他减少',
  `daily_livestock_on_hand` double(12,2) DEFAULT NULL COMMENT ' 日均存栏',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_resevers_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=71532 DEFAULT CHARSET=utf8 COMMENT='后备区报表';

-- Create syntax for TABLE 'doctor_report_sows'
CREATE TABLE `doctor_report_sows` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sum_at` date NOT NULL,
  `sum_at_name` varchar(32) NOT NULL DEFAULT '',
  `date_type` tinyint(4) NOT NULL COMMENT '日期类型，1->日,2->周,3->月,4->季,5->年',
  `orz_id` bigint(20) NOT NULL COMMENT '组织ID',
  `orz_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
  `orz_type` tinyint(4) NOT NULL COMMENT '组织类型，1->集团,2->公司，3->猪场',
  `start` int(11) NOT NULL COMMENT '期初存栏',
  `dead` varchar(512) NOT NULL DEFAULT '' COMMENT '死亡数量',
  `weed_out` varchar(512) NOT NULL DEFAULT '' COMMENT '淘汰数量',
  `dead_weed_out_rate` double(14,4) DEFAULT NULL COMMENT ' 死淘率',
  `sale` varchar(512) NOT NULL COMMENT '销售数量',
  `chg_farm_out` int(11) NOT NULL COMMENT '转场数量',
  `other_change` int(11) NOT NULL COMMENT '其他减少',
  `houbei_in` int(11) NOT NULL COMMENT '后备转入',
  `other_in` int(11) NOT NULL COMMENT '其他转入',
  `daily_livestock_on_hand` double(12,2) DEFAULT NULL COMMENT ' 日均存栏',
  `end` int(11) NOT NULL COMMENT '期末存栏',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_report_sows_orz_id` (`orz_id`)
) ENGINE=InnoDB AUTO_INCREMENT=71634 DEFAULT CHARSET=utf8 COMMENT='母猪报表';

CREATE TABLE `doctor_report_npds` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `farm_id` bigint(20) DEFAULT NULL COMMENT '猪场',
  `org_id` bigint(20) DEFAULT NULL COMMENT '公司ID',
  `sum_at` date DEFAULT NULL COMMENT '报表日期,月度单位',
  `npd` int(11) DEFAULT NULL COMMENT '非生产总天数',
  `pregnancy` int(11) DEFAULT NULL COMMENT '怀孕期',
  `sow_count` int(11) DEFAULT NULL COMMENT '存栏。（母猪日存栏-进场未配种母猪数）',
  `days` int(11) DEFAULT NULL COMMENT '天数',
  `lactation` int(11) DEFAULT NULL COMMENT '哺乳期',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_farm_id` (`farm_id`)
) ENGINE=InnoDB AUTO_INCREMENT=690 DEFAULT CHARSET=utf8 COMMENT='猪场月度母猪非生产天数表';

CREATE TABLE `doctor_filed_urls` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL COMMENT '字段名称',
  `url` varchar(512) NOT NULL COMMENT '字段跳转url',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COMMENT='字段跳转url';

-- Create syntax for TABLE 'doctor_report_field_customizes'
CREATE TABLE `doctor_report_field_customizes` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `farm_id` bigint(20) NOT NULL COMMENT '猪场ID',
  `type_id` bigint(20) NOT NULL COMMENT '类型ID',
  `field_id` bigint(20) DEFAULT NULL COMMENT '字段ID',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_type` (`type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=45147 DEFAULT CHARSET=utf8 COMMENT='报表自定义可显示字段';

-- Create syntax for TABLE 'doctor_report_fields'
CREATE TABLE `doctor_report_fields` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `f_id` bigint(20) DEFAULT NULL COMMENT '父ID',
  `name` varchar(32) NOT NULL COMMENT '字段名称',
  `report_field` varchar(64) NOT NULL DEFAULT '' COMMENT '字段英文名称，对应九张报表中字段名',
  `type` smallint(6) DEFAULT NULL COMMENT '类型',
  `data_formatter` varchar(128) DEFAULT NULL COMMENT '数据格式处理类名',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=430 DEFAULT CHARSET=utf8 COMMENT='报表自定义字段表';

