package io.terminus.doctor.move.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by chenzenghui on 16/7/27.
 */
public class View_EventListSow implements Serializable {
    private String OID;
    private String Status;
    private String FarmOID;
    private String PigID;
    private String PigFatherID;
    private String PigMotherID;
    private String Source;
    private Date BirthDate;
    private Double BirthWeight;
    private Date HerdEntryDate;
    private Integer HerdEntryDays;
    private String InitLocation;
    private String Location;
    private Integer InitialParity;
    private Integer CurrentParity;
    private Integer LnippleCount;
    private Integer RnippleCount;
    private String Breed;
    private String Genetic;
    private String Remark;
    private Double Weight;
    private String Sex;
    private String HerdRemovalDate;
    private String EventOID;
    private String Srm;
    private String PigAltID;
    private String EOID;
    private Integer Parity;
    private Date EventDate;
    private String EventName;
    private String EventDetail;
    private String RelMainOID;
    private String ERemark;
    private String EventType;
    private String EventEName;
    private String EventLocation;
    private String BoarID;
    private String ServiceType;
    private String Staff;
    private String ServiceTime;
    private Date DueToFarrowDate;
    private String PregChkResult;
    private Integer LitterID;
    private String FarrowingType;
    private Integer MidWife;
    private Integer MidWife2;
    private Integer AliveSow;
    private Integer AliveBoar;
    private Boolean FarrowNeedAssisted;
    private Double EWeight;
    private Integer allCount;
    private Integer BornAlive;
    private Integer BornDead;
    private Integer BornMummified;
    private Integer BornJx;
    private Integer BornRz;
    private Integer BornBlack;
    private Integer ChgCount;
    private String ChgType;
    private String ChgReason;
    private Double Price;
    private Double SumJe;
    private String Customer;
    private String NurseSow;
    private Integer NetInPiglets;
    private Integer NetOutPiglets;
    private String OutDestination;
    private String Disease;
    private String Treament;
    private Integer Score;
    private Double BackFat;
    private Integer WeanCount;
    private Double WeanWeight;
    private String Operator;
    private String AutoGenerate;
    private String RelEventOID;
    private String GainCloseEventOID;
    private String CurrentGainOID;
    private String FarmOIDText;
    private String LocationCaption;
    private String OldPigTypeOID;
    private String OldTypeName;
    private String CurrentLocationCaption;
    private String PigTypeOID;
    private String TypeName;
}
