package io.terminus.doctor.move.model;

import java.io.Serializable;

/**
 * Created by chenzenghui on 16/7/27.
 */
public class View_EventListSow implements Serializable {
    private String OID;
    private String Status;
    private String FarmOID;
    private String PigID;
    private String PigFatherID;
    private String PigMotherID;
    private String Source;
    private String BirthDate;
    private String BirthWeight;
    private String HerdEntryDate;
    private String HerdEntryDays;
    private String InitLocation;
    private String Location;
    private String InitialParity;
    private String CurrentParity;
    private String LnippleCount;
    private String RnippleCount;
    private String Breed;
    private String Genetic;
    private String Remark;
    private String Weight;
    private String Sex;
    private String HerdRemovalDate;
    private String EventOID;
    private String Srm;
    private String PigAltID;
    private String EOID;
    private String Parity;
    private String EventDate;
    private String EventName;
    private String EventDetail;
    private String RelMainOID;
    private String ERemark;
    private String EventType;
    private String EventEName;
    private String EventLocation;
    private String BoarID;
    private String ServiceType;
    private String Staff;
    private String ServiceTime;
    private String DueToFarrowDate;
    private String PregChkResult;
    private String LitterID;
    private String FarrowingType;
    private String MidWife;
    private String MidWife2;
    private String AliveSow;
    private String AliveBoar;
    private String FarrowNeedAssisted;
    private String EWeight;
    private String allCount;
    private String BornAlive;
    private String BornDead;
    private String BornMummified;
    private String BornJx;
    private String BornRz;
    private String BornBlack;
    private String ChgCount;
    private String ChgType;
    private String ChgReason;
    private String Price;
    private String SumJe;
    private String Customer;
    private String NurseSow;
    private String NetInPiglets;
    private String NetOutPiglets;
    private String OutDestination;
    private String Disease;
    private String Treament;
    private String Score;
    private String BackFat;
    private String WeanCount;
    private String WeanWeight;
    private String Operator;
    private String AutoGenerate;
    private String RelEventOID;
    private String GainCloseEventOID;
    private String CurrentGainOID;
    private String FarmOIDText;
    private String LocationCaption;
    private String OldPigTypeOID;
    private String OldTypeName;
    private String CurrentLocationCaption;
    private String PigTypeOID;
    private String TypeName;
}
