package io.terminus.doctor.user.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.user.model.DoctorServiceStatus;

/**
 * Code generated by terminus code gen
 * Desc: 用户服务状态表写服务
 * Date: 2016-06-03
 */

public interface DoctorServiceStatusWriteService {

    /**
     * 创建DoctorServiceStatus
     * @param serviceStatus
     * @return 主键id
     */
    Response<Long> createServiceStatus(DoctorServiceStatus serviceStatus);

    /**
     * 更新DoctorServiceStatus
     * @param serviceStatus
     * @return 是否成功
     */
    Response<Boolean> updateServiceStatus(DoctorServiceStatus serviceStatus);

    /**
     * 根据主键id删除DoctorServiceStatus
     * @param id 主键
     * @return 是否成功
     */
    Response<Boolean> deleteById(Long id);

    /**
     * 初始化用户各项服务的状态, 即向表中插入一条数据, 所有服务都是未开通状态
     * @param userId 用户id
     * @return 是否成功
     */
    Response<Boolean> initDefaultServiceStatus(Long userId);
}