package io.terminus.doctor.user.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.user.dto.DoctorServiceStatusDto;
import io.terminus.doctor.user.model.DoctorServiceStatus;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 用户服务状态表读服务
 * Date: 2016-06-03
 */

public interface DoctorServiceStatusReadService {

    /**
     * 根据id查询用户服务状态表
     * @param serviceStatusId 主键id
     * @return 用户服务状态表
     */
    Response<DoctorServiceStatus> findServiceStatusById(Long serviceStatusId);

    /**
     * 根据userId查询用户的服务开通情况
     * @param userId
     * @return
     */
    Response<DoctorServiceStatus> findByUserId(Long userId);

    /**
     * 查询用户服务开通情况dto
     * @param userId
     * @return
     */
    Response<DoctorServiceStatusDto> findDoctorServiceStatusDto(Long userId);
}
