package io.terminus.doctor.user.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.user.model.DoctorServiceReview;
import io.terminus.doctor.user.model.ServiceReviewTrack;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 读服务
 * Date: 2016-05-31
 */

public interface ServiceReviewTrackReadService {

    /**
     * 根据id查询
     * @param serviceReviewTrackId 主键id
     * @return 
     */
    Response<ServiceReviewTrack> findServiceReviewTrackById(Long serviceReviewTrackId);

    Response<List<ServiceReviewTrack>> findByUserId(Long userId);

    Response<List<ServiceReviewTrack>> findByUserIdAndType(Long userId, DoctorServiceReview.Type type);

    Response<ServiceReviewTrack> findLastByUserIdAndType(Long userId, DoctorServiceReview.Type type);
}
