package io.terminus.doctor.user.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.user.model.ServiceReviewTrack;

/**
 * Code generated by terminus code gen
 * Desc: 写服务
 * Date: 2016-05-31
 */

public interface ServiceReviewTrackWriteService {

    /**
     * 创建DoctorServiceReviewTrack
     * @param serviceReviewTrack
     * @return 主键id
     */
    Response<Long> createServiceReviewTrack(ServiceReviewTrack serviceReviewTrack);

    /**
     * 更新DoctorServiceReviewTrack
     * @param serviceReviewTrack
     * @return 是否成功
     */
    Response<Boolean> updateServiceReviewTrack(ServiceReviewTrack serviceReviewTrack);

    /**
     * 根据主键id删除DoctorServiceReviewTrack
     * @param serviceReviewTrackId
     * @return 是否成功
     */
    Response<Boolean> deleteServiceReviewTrackById(Long serviceReviewTrackId);
}