package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorDailyGroup;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数量每天记录表读服务
 * Date: 2017-04-17
 */

public interface DoctorDailyGroupReadService {

    /**
     * 根据id查询猪群数量每天记录表
     * @param doctorDailyGroupId 主键id
     * @return 猪群数量每天记录表
     */
    Response<DoctorDailyGroup> findDoctorDailyGroupById(Long doctorDailyGroupId);

    Response<List<DoctorDailyGroup>> findGroupInfoBySumAt(String sumAt);
}
