package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorDailyGroup;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数量每天记录表写服务
 * Date: 2017-04-17
 */

public interface DoctorDailyGroupWriteService {

    /**
     * 创建DoctorDailyGroup
     * @param doctorDailyGroup
     * @return 主键id
     */
    Response<Long> createDoctorDailyGroup(DoctorDailyGroup doctorDailyGroup);

    /**
     * 更新DoctorDailyGroup
     * @param doctorDailyGroup
     * @return 是否成功
     */
    Response<Boolean> updateDoctorDailyGroup(DoctorDailyGroup doctorDailyGroup);

    /**
     * 根据主键id删除DoctorDailyGroup
     * @param doctorDailyGroupId
     * @return 是否成功
     */
    Response<Boolean> deleteDoctorDailyGroupById(Long doctorDailyGroupId);

    /**
     * 生成每天的group daily
     * @param allFarmIds
     * @param yesterday
     * @return
     */
    Response<Boolean> createDailyGroups(List<Long> allFarmIds, Date yesterday);

    Response<Boolean> createDailyGroups(Long farmIds, Date yesterday);
}