package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorBoarMonthlyReport;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 公猪生产成绩月报读服务
 * Date: 2016-09-12
 */

public interface DoctorBoarMonthlyReportReadService {

    /**
     * 根据id查询公猪生产成绩月报
     * @param doctorBoarMonthlyReportId 主键id
     * @return 公猪生产成绩月报
     */
    Response<DoctorBoarMonthlyReport> findDoctorBoarMonthlyReportById(Long doctorBoarMonthlyReportId);
}
