package io.terminus.doctor.event.service;

import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorVaccinationPigWarn;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 猪只设置免疫程序统计方式读服务
 * Date: 2016-06-13
 */

public interface DoctorVaccinationPigWarnReadService {

    /**
     * 根据id查询猪只设置免疫程序统计方式
     * @param vaccinationPigWarnId 主键id
     * @return 猪只设置免疫程序统计方式
     */
    Response<DoctorVaccinationPigWarn> findVaccinationPigWarnById(Long vaccinationPigWarnId);

    /**
     * 分页获取猪只免疫程序
     * @param pageNo    第一页
     * @param pageSize  页大小
     * @param farmId    猪场id
     * @return
     */
    Response<Paging<DoctorVaccinationPigWarn>> pagingVaccPigWarns(Integer pageNo, Integer pageSize, Long farmId);

    /**
     * 查询猪只免疫规则列表
     * @param farmId 猪场id
     * @return
     */
    Response<List<DoctorVaccinationPigWarn>>findVaccinationPigWarnsByFarmId(Long farmId);

    /**
     * 查询猪只免疫规则列表
     * @param criteria  查询参数
     * @return
     */
    Response<List<DoctorVaccinationPigWarn>>findVaccinationPigWarns(Map<String, Object> criteria);
}
