package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorVaccinationPigWarn;

/**
 * Code generated by terminus code gen
 * Desc: 猪只设置免疫程序统计方式写服务
 * Date: 2016-06-13
 */

public interface DoctorVaccinationPigWarnWriteService {

    /**
     * 创建DoctorVaccinationPigWarn
     * @param vaccinationPigWarn
     * @return 主键id
     */
    Response<Long> createVaccinationPigWarn(DoctorVaccinationPigWarn vaccinationPigWarn);

    /**
     * 更新DoctorVaccinationPigWarn
     * @param vaccinationPigWarn
     * @return 是否成功
     */
    Response<Boolean> updateVaccinationPigWarn(DoctorVaccinationPigWarn vaccinationPigWarn);

    /**
     * 根据主键id删除DoctorVaccinationPigWarn
     * @param vaccinationPigWarnId
     * @return 是否成功
     */
    Response<Boolean> deleteVaccinationPigWarnById(Long vaccinationPigWarnId);
}