package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorDailyReport;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 日报写服务
 * Date: 2017-04-19
 */

public interface DoctorDailyReportWriteService {

    /**
     * 创建DoctorDailyReport
     * @param doctorDailyReport
     * @return 主键id
     */
    Response<Long> createDoctorDailyReport(DoctorDailyReport doctorDailyReport);

    /**
     * 更新DoctorDailyReport
     * @param doctorDailyReport
     * @return 是否成功
     */
    Response<Boolean> updateDoctorDailyReport(DoctorDailyReport doctorDailyReport);

    /**
     * 根据主键id删除DoctorDailyReport
     * @param doctorDailyReportId
     * @return 是否成功
     */
    Response<Boolean> deleteDoctorDailyReportById(Long doctorDailyReportId);

    /**
     * 统计前一天和今天的日报
     * @param allFarmIds
     * @return
     */
    Response<Boolean> generateYesterdayAndTodayReports(List<Long> allFarmIds);

    /**
     * 生产一段时间的日报
     * @param farmId
     * @param startAt
     * @param endAt
     */
    Response<Boolean> createDailyReports(Long farmId, Date startAt, Date endAt);

    /**
     * 生成所有猪场的日报
     * @param farmIds
     * @param startAt
     */
    Response<Boolean> createDailyReports(List<Long> farmIds, Date startAt);
}