package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorParityMonthlyReport;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 胎次产仔分析月报写服务
 * Date: 2016-09-13
 */

public interface DoctorParityMonthlyReportWriteService {

    /**
     * 创建DoctorParityMonthlyReport
     * @param doctorParityMonthlyReport
     * @return 主键id
     */
    Response<Long> createDoctorParityMonthlyReport(DoctorParityMonthlyReport doctorParityMonthlyReport);

    /**
     * 更新DoctorParityMonthlyReport
     * @param doctorParityMonthlyReport
     * @return 是否成功
     */
    Response<Boolean> updateDoctorParityMonthlyReport(DoctorParityMonthlyReport doctorParityMonthlyReport);

    /**
     * 根据主键id删除DoctorParityMonthlyReport
     * @param doctorParityMonthlyReportId
     * @return 是否成功
     */
    Response<Boolean> deleteDoctorParityMonthlyReportById(Long doctorParityMonthlyReportId);


    /**
     * 猪场产仔分析月报
     * @param farmIds
     * @param sumAt
     * @return
     */
    Response<Boolean> createMonthlyReports(List<Long> farmIds, Date sumAt);

    /**
     * 猪场产仔分析月报
     * @param farmId
     * @param sumAt
     * @return
     */
    Response<Boolean> createMonthlyReport(Long farmId, Date sumAt);
}