package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.dto.search.SearchedBarn;
import io.terminus.doctor.event.model.DoctorDailyPig;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪数量每天记录表写服务
 * Date: 2017-04-17
 */

public interface DoctorDailyPigWriteService {

    /**
     * 创建DoctorDailyPig
     * @param doctorDailyPig
     * @return 主键id
     */
    Response<Long> createDoctorDailyPig(DoctorDailyPig doctorDailyPig);

    /**
     * 更新DoctorDailyPig
     * @param doctorDailyPig
     * @return 是否成功
     */
    Response<Boolean> updateDoctorDailyPig(DoctorDailyPig doctorDailyPig);

    /**
     * 根据主键id删除DoctorDailyPig
     * @param doctorDailyPigId
     * @return 是否成功
     */
    Response<Boolean> deleteDoctorDailyPigById(Long doctorDailyPigId);

    /**
     *
     * @param farmIds
     * @param date
     * @return
     */
    Response<Boolean> createDailyPigs(List<Long> farmIds, Date date);

    /**
     *
     * @param farmId
     * @param date
     * @return
     */
    Response<Boolean> createDailyPigs(Long farmId, Date date);

}