package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorDailyPig;

/**
 * Code generated by terminus code gen
 * Desc: 猪数量每天记录表读服务
 * Date: 2017-04-17
 */

public interface DoctorDailyPigReadService {

    /**
     * 根据id查询猪数量每天记录表
     * @param doctorDailyPigId 主键id
     * @return 猪数量每天记录表
     */
    Response<DoctorDailyPig> findDoctorDailyPigById(Long doctorDailyPigId);
}
