package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.dto.report.daily.DoctorDailyReportDto;
import io.terminus.doctor.event.model.DoctorDailyReport;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 日报读服务
 * Date: 2017-04-19
 */

public interface DoctorDailyReportReadService {

    /**
     * 根据id查询日报
     * @param doctorDailyReportId 主键id
     * @return 日报
     */
    Response<DoctorDailyReport> findDoctorDailyReportById(Long doctorDailyReportId);

    /**
     * 根据farmId,date查询日报
     * @param farmId
     * @param date
     * @return
     */
    Response<DoctorDailyReport> findDailyReportByFarmIdAndSumAt(Long farmId, String date);

    /**
     * 根据farmId,startAt,endAt查询范围内的报表
     * @param farmId
     * @param startAt
     * @param endAt
     * @return
     */
    Response<List<DoctorDailyReport>> findDailyReportByFarmIdAndRange(Long farmId, String startAt, String endAt);

    /**
     * 查询日报DoctorDailyReportDto,包含指标
     * @param farmId
     * @param date
     * @return
     */
    Response<DoctorDailyReportDto> findDailyReportDtoByFarmIdAndSumAt(Long farmId, String date);

    /**
     * 查询DoctorDailyReportDto范围
     * @param farmId
     * @param startAt
     * @param endAt
     * @return
     */
    Response<List<DoctorDailyReportDto>> findDailyReportDtoByFarmIdAndRange(Long farmId, String startAt, String endAt);

    /**
     * 根据日期查询日报
     * @param date
     * @return
     */
    Response<List<DoctorDailyReport>> findDailyReportBySumAt(Date date);
}
