package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorGroupInfoCheck;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 猪群数据校验表读服务
 * Date: 2017-03-25
 */

public interface DoctorGroupInfoCheckReadService {

    /**
     * 根据id查询猪群数据校验表
     * @param doctorGroupInfoCheckId 主键id
     * @return 猪群数据校验表
     */
    Response<DoctorGroupInfoCheck> findDoctorGroupInfoCheckById(Long doctorGroupInfoCheckId);

}
