package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorRangeReport;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报读服务
 * Date: 2017-04-19
 */

public interface DoctorRangeReportReadService {

    /**
     * 根据id查询指标月报
     * @param doctorRangeReportId 主键id
     * @return 指标月报
     */
    Response<DoctorRangeReport> findDoctorRangeReportById(Long doctorRangeReportId);
}
