package io.terminus.doctor.event.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.event.model.DoctorRangeReport;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 指标月报写服务
 * Date: 2017-04-19
 */

public interface DoctorRangeReportWriteService {

    /**
     * 创建DoctorRangeReport
     * @param doctorRangeReport
     * @return 主键id
     */
    Response<Long> createDoctorRangeReport(DoctorRangeReport doctorRangeReport);

    /**
     * 更新DoctorRangeReport
     * @param doctorRangeReport
     * @return 是否成功
     */
    Response<Boolean> updateDoctorRangeReport(DoctorRangeReport doctorRangeReport);

    /**
     * 根据主键id删除DoctorRangeReport
     * @param doctorRangeReportId
     * @return 是否成功
     */
    Response<Boolean> deleteDoctorRangeReportById(Long doctorRangeReportId);

    /**
     * 生产周报、月报
     * @param farmIds
     * @param today
     * @return
     */
    Response<Boolean> generateDoctorRangeReports(List<Long> farmIds, Date today);

    /**
     * 生成公司月报
     * @param orgMap 公司id 与其下猪场id映射
     * @param since 开始月份
     * @return
     */
    Response<Boolean> generateOrgDoctorRangeReports(Map<Long, List<Long>> orgMap, Date since);

    Response<Boolean> generateDoctorRangeReports(Long farmId, Date date);

    /**
     * 刷历史数据报表,刷当前月,当前5周的报表
     * @param farmId
     * @param date
     * @return
     */
    Response<Boolean> flushDoctorRangeReports(Long farmId, Date date);

    /**
     * 更新某一段时间的周报、月报存栏结构
     * @param fid
     * @param startAt
     * @param endAt
     * @return
     */
    Response<Boolean> updateStructureReport(Long fid, Date startAt, Date endAt);
}