package io.terminus.doctor.web.front.basic.controller;

import io.terminus.boot.rpc.common.annotation.RpcConsumer;
import io.terminus.doctor.basic.model.DoctorFarmBasic;
import io.terminus.doctor.basic.service.DoctorFarmBasicReadService;
import io.terminus.doctor.basic.service.DoctorFarmBasicWriteService;
import io.terminus.parana.common.utils.RespHelper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Code generated by CodeGen
 * Desc: 猪场基础数据关联表 Controller
 * Date: 2016-11-22
 */
@Slf4j
@RestController
@RequestMapping("/api/doctor")
public class DoctorFarmBasics {

    @RpcConsumer
    private DoctorFarmBasicReadService doctorFarmBasicReadService;

    @RpcConsumer
    private DoctorFarmBasicWriteService doctorFarmBasicWriteService;

    /**
     * 根据id查询猪场基础数据关联表
     * @param farmId 猪场id
     * @return 猪场基础数据关联表
     */
    @RequestMapping(value = "/farmBasic/id", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public DoctorFarmBasic findFarmBasicById(@RequestParam("farmId") Long farmId) {
        return RespHelper.or500(doctorFarmBasicReadService.findFarmBasicByFarmId(farmId));
    }

    /**
     * 创建或更新DoctorFarmBasic
     * @return 是否成功
     */
    @RequestMapping(value = "/farmBasic", method = RequestMethod.POST)
    public Boolean createOrUpdateFarmBasic(@RequestBody DoctorFarmBasic farmBasic) {
        checkNotNull(farmBasic, "farmBasic.not.null");

        if (farmBasic.getId() == null) {
            RespHelper.or500(doctorFarmBasicWriteService.createFarmBasic(farmBasic));
        } else {
            RespHelper.or500(doctorFarmBasicWriteService.updateFarmBasic(farmBasic));
        }
        return Boolean.TRUE;
    }
}