package io.terminus.doctor.msg.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.msg.model.DoctorMessageRule;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则表Dao类
 * Date: 2016-05-30
 * author: chk@terminus.io
 */
@Repository
public class DoctorMessageRuleDao extends MyBatisDao<DoctorMessageRule> {

}
