package io.terminus.doctor.msg.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.msg.model.DoctorMessage;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息表Dao类
 * Date: 2016-05-30
 * Author: chk@terminus.io
 */
@Repository
public class DoctorMessageDao extends MyBatisDao<DoctorMessage> {

    /**
     * 获取未读站内信的数量
     * @param userId    用户id
     * @return
     */
    public Long findNoReadCount(Long userId) {
        return getSqlSession().selectOne(sqlId("findNoReadCount"), userId);
    }

}
