package io.terminus.doctor.msg.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.msg.model.DoctorMessageRuleTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 猪场软件消息规则模板表Dao类
 * Date: 2016-05-31
 * Author: chk@terminus.io
 */
@Repository
public class DoctorMessageRuleTemplateDao extends MyBatisDao<DoctorMessageRuleTemplate> {



    /**
     * 根据消息种类获取对应的默认消息模板
     * @param category
     *          @see io.terminus.doctor.msg.enums.Category
     * @return
     */
    public List<DoctorMessageRuleTemplate> findByCategory(Integer category) {
        return getSqlSession().selectList(sqlId("findByCategory"), category);
    }

    /**
     * 获取所有的预警和警报消息
     * @return
     */
    public List<DoctorMessageRuleTemplate> findAllWarnMessageTpl() {
        return getSqlSession().selectList(sqlId("findAllWarnMessageTpl"));
    }

    /**
     * 获取所有未删除的消息模板
     * @param criteria  查询条件
     * @return
     */
    public List<DoctorMessageRuleTemplate> listNotDelete(Map<String, Object> criteria) {
        return getSqlSession().selectList(sqlId("listNotDelete"), criteria);
    }
}
