package io.terminus.doctor.warehouse.model;

import io.terminus.common.utils.JsonMapper;
import io.terminus.doctor.warehouse.dto.EventHandlerContext;
import lombok.Data;
import lombok.experimental.Builder;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 仓库物资每次出库和入库事件之前的快照Model类
 * Date: 2016-09-21
 */
@Data
@Builder
public class DoctorWarehouseSnapshot implements Serializable {

    private static final long serialVersionUID = 5934588860923527558L;
    private Long id;
    
    /**
     * 表doctor_material_consume_providers的id
     */
    private Long eventId;
    
    /**
     * 事件之前的状态
     */
    private String beforeEvent;
    
    private Date createdAt;
    
    private Date updatedAt;

    public EventHandlerContext.Snapshot json2Snapshot(){
        return JsonMapper.nonEmptyMapper().fromJson(this.beforeEvent, EventHandlerContext.Snapshot.class);
    }
}
