package io.terminus.doctor.warehouse.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 饲料配方表Model类
 * Date: 2016-09-26
 */
@Data
public class FeedFormula implements Serializable {
    private static final long serialVersionUID = -7638873685503008738L;

    private Long id;
    
    /**
     * 饲料id
     */
    private Long feedId;
    
    /**
     * 饲料名称
     */
    private String feedName;
    
    /**
     * 猪场id
     */
    private Long farmId;
    
    /**
     * 猪场名称
     */
    private String farmName;
    
    /**
     * 配方json
     */
    private String formula;
    
    private Date createdAt;
    
    private Date updatedAt;
}
