spring:
  profiles:
    include: zookeeper

# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.doctor.event.model,io.terminus.doctor.workflow.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://101.201.44.35:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: anywhere

# Dubbo
rpc.mode: true
rpc.dubbo:
    module: doctor-event
    registryAddress: 101.201.44.35:2181
    version: 1.0.0

logging:
  file: /var/log/doctor/event.log
  level.*: INFO

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181
  zkTopic: pig.doctor.topic

# Redis
redis:
  host: 101.201.44.35
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# search
search:
  host: 127.0.0.1
  port: 9200

flow:
  definition:
    key:
      sow: sow
      boar: boar