package io.terminus.doctor.basic.service;

import com.google.common.base.Throwables;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.exception.ServiceException;
import io.terminus.common.model.Response;
import io.terminus.common.utils.JsonMapper;
import io.terminus.doctor.basic.dao.FeedFormulaDao;
import io.terminus.doctor.basic.dto.DoctorWareHouseBasicDto;
import io.terminus.doctor.basic.manager.MaterialInWareHouseManager;
import io.terminus.doctor.basic.model.DoctorWareHouse;
import io.terminus.doctor.basic.model.FeedFormula;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 饲料配方表写服务实现类
 * Date: 2016-09-26
 */
@Slf4j
@Service
@RpcProvider
public class FeedFormulaWriteServiceImpl implements FeedFormulaWriteService {

    private final FeedFormulaDao feedFormulaDao;
    private final MaterialInWareHouseManager materialInWareHouseManager;

    @Autowired
    public FeedFormulaWriteServiceImpl(FeedFormulaDao feedFormulaDao,
                                       MaterialInWareHouseManager materialInWareHouseManager) {
        this.feedFormulaDao = feedFormulaDao;
        this.materialInWareHouseManager = materialInWareHouseManager;
    }

    @Override
    public Response<Long> createFeedFormula(FeedFormula feedFormula) {
        try {
            feedFormulaDao.create(feedFormula);
            return Response.ok(feedFormula.getId());
        } catch (Exception e) {
            log.error("create feedFormula failed, feedFormula:{}, cause:{}", feedFormula, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.create.fail");
        }
    }

    @Override
    public Response<Boolean> updateFeedFormula(FeedFormula feedFormula) {
        try {
            return Response.ok(feedFormulaDao.update(feedFormula));
        } catch (Exception e) {
            log.error("update feedFormula failed, feedFormula:{}, cause:{}", feedFormula, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.update.fail");
        }
    }

    @Override
    public Response<Boolean> deleteFeedFormulaById(Long feedFormulaId) {
        try {
            return Response.ok(feedFormulaDao.delete(feedFormulaId));
        } catch (Exception e) {
            log.error("delete feedFormula failed, feedFormulaId:{}, cause:{}", feedFormulaId, Throwables.getStackTraceAsString(e));
            return Response.fail("feedFormula.delete.fail");
        }
    }

    @Override
    public Response<Boolean> produceFeedByFormula(DoctorWareHouseBasicDto basicDto, DoctorWareHouse targetHouse, FeedFormula feedFormula,
                                                  Long feedUnitId, String feedUnitName, FeedFormula.FeedProduce materialProduce){
        try{
            return Response.ok(materialInWareHouseManager.produceMaterialInfo(basicDto, targetHouse, feedFormula, feedUnitId, feedUnitName, materialProduce));
        }catch(ServiceException | IllegalStateException e){
            return Response.fail(e.getMessage());
        }catch(Exception e){
            log.error("real material produce fail, cause:{}", Throwables.getStackTraceAsString(e));
            return Response.fail("produce.realMaterial.fail");
        }
    }

    @Override
    public Response<FeedFormula.FeedProduce> produceMaterial(Long materialId, Double produceCount) {
        try{
            // get material
            FeedFormula doctorMaterialInfo = feedFormulaDao.findById(materialId);
            if(doctorMaterialInfo == null){
                return Response.fail("input.materialId.error");
            }

            // 校验对应的原料生产信息
            if(!doctorMaterialInfo.getExtraMap().containsKey("materialProduce")){
                return Response.fail("material.percentRatio.error");
            }

            FeedFormula.FeedProduce materialProduce = JsonMapper.JSON_NON_DEFAULT_MAPPER.fromJson(
                    doctorMaterialInfo.getExtraMap().get("materialProduce"), FeedFormula.FeedProduce.class);

            // count ration
            materialProduce.calculatePercentByTotal(produceCount);
            return Response.ok(materialProduce);
        }catch (Exception e){
            log.error("material produce error, cause:{}", Throwables.getStackTraceAsString(e));
            return Response.fail("produce.material.fail");
        }
    }
}
